Esri/arcgis-maps-sdk-swift-samples

Shared/Samples/Project geometry/ProjectGeometryView.swift

This PR fixes `Project` sample.
- close #92 
- Scroll horizontally. In the past the x value will monotonically increase/decrease; with this fix the coordinates will remain the same

[Fix] Wraparound meridian in `Project` sample

---

README.md
Shared/Supporting Files/Views/AboutView.swift

This PR updates the remaining occurrences of "runtime" in this project, to "maps". No more "runtime" should be found in this repo.

[Update] GeoNet URL, Runtime > Maps

---

Shared/Samples/Add feature layers/AddFeatureLayersView.swift

This PR uses the latest auth API.
- `swift/issues/3220`
- https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/231
Make sure it still builds.

[Update] API name

---

Shared/Samples/Add feature layers/AddFeatureLayersView.swift
Shared/Samples/Add scene layer from service/AddSceneLayerFromServiceView.swift
Shared/Samples/Set surface placement mode/SetSurfacePlacementModeView.swift
Shared/Samples/Show viewshed from point in scene/ShowViewshedFromPointInSceneView.Model.swift

This PR fixes the build with latest API.
-  close #115 
Run the changed samples and see if they behave correctly.

[Update] Use latest API signature

---

Shared/Samples/Project geometry/ProjectGeometryView.swift
Shared/Samples/Set basemap/SetBasemapView.swift
Shared/Samples/Show callout/ShowCalloutView.swift
Shared/Samples/Show result of spatial relationships/ShowResultOfSpatialRelationshipsView.swift

This PR fixes…
- #109 , slow down the callout animation by half
- #110 , remove the extra `esriBorder`

[Update] Address UI related feedback

---

Shared/Samples/Project geometry/ProjectGeometryView.swift
Shared/Samples/Search with geocode/SearchWithGeocodeView.swift
Shared/Samples/Show callout/ShowCalloutView.swift
Shared/Samples/Show result of spatial relationships/ShowResultOfSpatialRelationshipsView.swift

This PR updates the usages of `CalloutPlacement`.
- `swift/issues/3609`
Try the changed samples and see if they behave correctly.

[Update] `CalloutPlacement` API signature

---

Shared/Samples/Show viewshed from point in scene/ShowViewshedFromPointInSceneView.Model.swift

This PR updates the API.
- `swift/pull/3733`
Build and run without error.

[Update] Make the `LocationViewshed` initializer not optional

---

Shared/Samples/Authenticate with OAuth/AuthenticateWithOAuthView.swift

This PR updates `Authenticate with OAuth` in `Cloud and portal` category.

[Update] Authenticate with OAuth: added persistent credential code and comments

---

Shared/Samples/Sketch on map/SketchOnMapView.swift

Simplifies checking whether the geometry can be saved.

[Update] Use `Geometry.sketchIsValid`

---

Shared/Samples/Authenticate with OAuth/AuthenticateWithOAuthView.swift
Shared/Samples/Sketch on map/SketchOnMapView.swift

This PR fixes compiler warnings and error.

[Update] Fix compiling issues

---

README.md
Samples.xcodeproj/project.pbxproj
iOS/Info.plist

This PR fixes a plist order issue, and bumps the version number to 200.1.

[Update] Bump version number for 200.1.0

---

README.md
Samples.xcodeproj/project.pbxproj
Shared/Supporting Files/Views/AboutView.swift

This PR updates the year in README and the version number in Xcode.
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/162#discussion_r1163243611

[Update] Year and version

---

Shared/Samples/Set viewpoint rotation/SetViewpointRotationView.swift

- Makes use of the new Compass API signature
- To be merged following [Toolkit #298](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/298)

[Update] Adjust Compass API signature

---

Shared/Samples/Query feature table/README.md

This PR fixes a wrong image filepath in README.

[Update] Fix image path for `Query feature table`

---

Samples.xcodeproj/project.pbxproj
Shared/Samples/Sketch on map/SketchOnMapView.swift
Shared/Samples/Trace utility network/TraceUtilityNetworkView.Model.swift
Shared/Samples/Trace utility network/TraceUtilityNetworkView.Views.swift

This PR updates the build phase. I'm using SwiftLint 0.51.0 to fix warnings.
See https://github.com/realm/SwiftLint#xcode

[Setup] Update SwiftLint shell script and fix linter warnings

---

README.md

[Fix] Bump requirement to Xcode 14.1 on v.next

---

Shared/Samples/Create load report/CreateLoadReportView.Model.swift
Shared/Samples/Create load report/CreateLoadReportView.swift
Shared/Samples/Measure distance in scene/MeasureDistanceInSceneView.swift

@des12437 here is some feedback for your PR that we discussed.  You can merge this into your branch via this PR if you'd like.

create load report pr feedback

---

Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.swift

Use the latest API for dynamic entity data source.
- `swift/pull/4393`
Build the app and there is no warning on this line.

[Update] Use latest API signature 

---

Shared/Samples/Create and save KML file/CreateAndSaveKMLView.swift
Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.Model.swift
Shared/Samples/Download vector tiles to local cache/DownloadVectorTilesToLocalCacheView.swift
Shared/Samples/Generate offline map/GenerateOfflineMapView.swift

This PR fixes a bug in temporary directory creation in iOS 17 beta on device.
There is a [File system changes introduced in iOS 17](https://developer.apple.com/forums/thread/733642) that puts the app bundle to a different volume on disk than its document/temporary and other data container directories. This made the old approach of getting the URL to the app-specific temporary directory no longer valid.
The [url(for:in:appropriateFor:create:)](https://developer.apple.com/documentation/foundation/filemanager/1407693-url) API specified that…
- `appropriateFor url`: This parameter is ignored unless the directory parameter contains the value [FileManager.SearchPathDirectory.itemReplacementDirectory](https://developer.apple.com/documentation/foundation/filemanager/searchpathdirectory/itemreplace …

[Fix] Temporary directory creation

---

Shared/Samples/Filter features in scene/FilterFeaturesInSceneView.swift

Adds missing MainActor attribute to the class model to address [this](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/254#discussion_r1317709468) feedback.

[Fix] Filter features in scene

---

Samples.xcodeproj/project.pbxproj
Samples.xcodeproj/xcshareddata/xcschemes/Samples.xcscheme
Shared/Samples/Augment reality to fly over scene/AugmentRealityToFlyOverSceneView.swift
Shared/Supporting Files/Extensions/View+Sheet.swift

This PR cleans up 3 issues in the project.
1. Update project to recommended settings for Xcode 15
2. Fix linter warning
3. Fix naming collision

[Update] Project cleanup

---

Samples.xcodeproj/project.pbxproj
Shared/PrivacyInfo.xcprivacy

These are the things that need to be declared in the privacy manifest if we collect any of this info:
* [Describing data use](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)
- [Required Use APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
I only listed in the privacy manifest that we use course location for a qualified reason. I didn't see any other items we need to list, please confirm this as a part of reviewing this PR.
Here is the privacy report for the Samples:
[Samples-PrivacyReport 2023-11-08 15-52-45.pdf](https://github.com/Esri/arcgis-maps-sdk-swift-samples/files/13302445/Samples-PrivacyReport.2023-11-08.15-52-45.pdf)
- …

[Setup] Add Privacy Manifest

---

Shared/Samples/Create mobile geodatabase/CreateMobileGeodatabaseView.Model.swift
Shared/Samples/Create mobile geodatabase/CreateMobileGeodatabaseView.swift

This PR implements a fix to a bug in the `Create mobile geodatabase` sample where the Sample Viewer would crash when the share button was pressed while it was running on-device. The solution was to replace the `UIActivityViewController` with `View.fileExporter`, which required refactoring much of the sample. Now, it is structured similarly to the `Create and save KML` sample.
URL to README: [README](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/Fix-CreateMobileGeodatabaseFileExporting/Shared/Samples/Create%20mobile%20geodatabase)
- `swift/issues/4791`
- Open the sample on-device.
- Tap on the map to add features to the feature table.
- Tap the share button in the bottom-right to export the geodatabase file.

[Fix] Create mobile geodatabase sharing crash

---

Shared/Samples/Create convex hull around geometries/CreateConvexHullAroundGeometriesView.swift

Close #217 per review feedback.
- #217 
- Check the UI on both iOS and Mac Catalyst.

[Update] Disable toggle when no convex hull is present

---

Shared/Samples/Show device location/README.md

This PR updates the doc for `Show device location` sample
- Close #229

[Update] Location permission documentation

---

Shared/Supporting Files/Views/AboutView.swift

Some redirect URLs need to be fixed.

[Update] AboutView URLs

---

Shared/Samples/Show device location with NMEA data sources/README.md

This PR updates the `Show device location with NMEA data sources` README to include the protocol for Emlid receivers  `com.emlid.nmea`.
- `swift/issues/5042`

[Update] Add Emlid NMEA protocol

---

README.md
Samples.xcodeproj/project.pbxproj

This PR bumps the samples and toolkit version numbers to `200.4.0`.

[Update] Bump version numbers for 200.4.0

---

Shared/Samples/Validate utility network topology/README.md

This PR updates the `Validate utility network topology` sample's README to include an "Additional information" section describing the Advanced Editing extension requirements. See the design updates in `common-samples/3908`.
URL to README: [README](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/Update-ValidateUtilityNetworkTopologyREADME/Shared/Samples/Validate%20utility%20network%20topology)
- `swift/issues/5006`

[Update] Validate utility network topology README

---

Shared/Samples/Authenticate with OAuth/README.md

This PR implements `Authenticate with OAuth`. Updates redirected and changed URLs.
- Close #378.

[Update] Redirected URLs in README for Authenticate with OAuth

---

Shared/Samples/Display dimensions/README.md

This PR updates `Display dimensions` README.
- Close #377

[Update] Remove Java link from Display dimensions

---

Shared/Samples/Augment reality to show hidden infrastructure/AugmentRealityToShowHiddenInfrastructureView.swift

This PR removes an unneeded `NavigationView` that prevented the map view from displaying on iPad in the `Augment reality to show hidden infrastructure` sample. The rest of the changes are just resulting indentation updates.
- N/A quick fix
- Add a pipe to the map.
- Ensure the AR scene view opens on both iPad and iPhone by tapping the camera button.

[Fix] `Augment reality to show hidden infrastructure` empty map

---

Shared/Samples/Monitor changes to layer view state/MonitorChangesToLayerViewStateView.swift
Shared/Samples/Monitor changes to layer view state/README.md

This PR replaces the outdated URLs in the `Monitor changes to layer view state` sample in response to [this feedback](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/395#discussion_r1580196300).
- N/A (quick fix)
- Ensure the data in the sample still loads.

[Fix] `Monitor changes to layer view state` URLs

---

Shared/Samples/Display clusters/README.md

This PR updates `Display clusters`.
- `common-samples/pull/3916`

[Update] Display clusters README to add info for graphics overlay

---

Shared/Samples/Add 3D tiles layer/Add3DTilesLayerView.swift

This PR updates `Add 3D tiles layer`.
Use publicly hosted service instead of test service. 
- `common-samples/pull/3925`
Sample behaves the same before and after.

[Update] 3D tileset to use public version

---

Shared/Samples/Browse OGC API feature service/BrowseOGCAPIFeatureServiceView.swift

This PR fixes a build error.
Build the app to both iOS and Mac Catalyst.

[Fix] Ambiguous Polygon symbol

---

Samples.xcodeproj/project.pbxproj

Fix for file that was left out of the build phase.

[Fix] Adds AddENCExchangeSetView to Copy Source Code Files in Build Phases

---

README.md

View README to see if changes are acceptable. 
[Reference Issue 445](https://github.com/Esri/arcgis-maps-sdk-swift-samples/issues/445)

[Enhancement] - Add App Store link to the root README - Issue 445

---

Samples.xcodeproj/xcshareddata/xcschemes/Samples.xcscheme

Apply suggested project check for Xcode 15.4.

[Update] Samples.xcscheme

---

Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.SettingsView.swift
Shared/Samples/Analyze network with subnetwork trace/AnalyzeNetworkWithSubnetworkTraceView.swift
Shared/Samples/Change map view background/ChangeMapViewBackgroundView.SettingsView.swift
Shared/Samples/Configure clusters/ConfigureClustersView.SettingsView.swift
Shared/Samples/Create load report/CreateLoadReportView.Views.swift
Shared/Samples/Display clusters/DisplayClustersView.swift
Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.MapPicker.swift
Shared/Samples/List spatial reference transformations/ListSpatialReferenceTransformationsView.swift
Shared/Samples/Manage operational layers/ManageOperationalLayersView.swift
Shared/Samples/Run valve isolation trace/RunValveIsolationTraceView.swift
Shared/Samples/Search for web map/SearchForWebMapView.Views.swift
Shared/Samples/Set up location-driven geotriggers/SetUpLocationDrivenGeotriggersView.swift
Shared/Samples/Set visibility of subtype sublayer/SetVisibilityOfSubtypeSublayerView.Views.swift
Shared/Samples/Show viewshed from point in scene/ShowViewshedFromPointInSceneView.ViewshedSettingsView.swift
Shared/Samples/Style symbols from mobile style file/StyleSymbolsFromMobileStyleFileView.SymbolOptionsListView.swift
Shared/Samples/Validate utility network topology/ValidateUtilityNetworkTopologyView.Views.swift
Shared/Supporting Files/Views/AboutView.swift
Shared/Supporting Files/Views/CategoriesView.swift
Shared/Supporting Files/Views/SampleLink.swift
Shared/Supporting Files/Views/SamplesSearchView.swift

[Referencing issue 409](https://github.com/Esri/arcgis-maps-sdk-swift-samples/issues/409)

[Fix] Change foregroundColor to foregroundStyle - Issue 409

---

Documentation/ConfigureAppSecrets.md
README.md
Shared/AppSecrets.swift.masque
Shared/Samples/Add ENC exchange set/README.md
Shared/Samples/Apply mosaic rule to rasters/README.md
Shared/Samples/Apply scheduled updates to preplanned map area/README.md
Shared/Samples/Augment reality to collect data/README.md
Shared/Samples/Augment reality to navigate route/README.md
Shared/Samples/Augment reality to show hidden infrastructure/README.md
Shared/Samples/Authenticate with OAuth/README.md
Shared/Samples/Create symbol styles from web styles/README.md
Shared/Samples/Download preplanned map area/README.md
Shared/Samples/Download vector tiles to local cache/README.md
Shared/Samples/Find address with reverse geocode/README.md
Shared/Samples/List spatial reference transformations/ListSpatialReferenceTransformationsView.swift
Shared/Samples/Query features with Arcade expression/README.md
Shared/Samples/Search with geocode/README.md
Shared/Samples/Set visibility of subtype sublayer/README.md
Shared/Samples/Show labels on layer/README.md
Shared/SamplesApp.swift

This PR updates various API key verbiage and replace redirected URLs to their destinations.
- Close #424 
- `swift/issues/5332`
- Read about API key phrasing and see if they make sense
- Check the URL before/after and see if the destinations are the same

[Update] API key verbiage in docs

---

Shared/Samples/Monitor changes to layer view state/MonitorChangesToLayerViewStateView.swift

[Referencing issue 400](https://github.com/Esri/arcgis-maps-sdk-swift-samples/issues/400)
[Which references this discussion](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/395#discussion_r1580239897)

[Fix] Change to formatted label - Issue 400 

---

Shared/Samples/Add custom dynamic entity data source/AddCustomDynamicEntityDataSourceView.Vessel.swift
Shared/Samples/Add features with contingent values/AddFeaturesWithContingentValuesView.Model.swift
Shared/Samples/Query features with Arcade expression/QueryFeaturesWithArcadeExpressionView.swift
Shared/Supporting Files/Views/WebView.swift

This PR fixes some concurrency warnings. 
To test, enable strict concurrency = complete from build settings.

[Fix] Strict concurrency warnings

---

Shared/Supporting Files/Views/CategoriesView.swift

Animates color change on selection and deselection of a category tile in the categories view.

[Update] Add animation for category selection - Issue 394

---

Shared/Samples/Create and edit geometries/CreateAndEditGeometriesView.swift

This PR fixes the ambiguous reference to `Polygon`.

[Fix] Create and edit geometries `Polygon` reference

---

Samples.xcodeproj/project.pbxproj
Samples.xcodeproj/xcshareddata/xcschemes/Samples.xcscheme
Shared/Samples/Augment reality to navigate route/AugmentRealityToNavigateRouteView.RoutePlannerView.swift
Shared/Samples/Edit feature attachments/EditFeatureAttachmentsView.swift
Shared/Samples/Find address with reverse geocode/FindAddressWithReverseGeocodeView.swift
Shared/Samples/Find route around barriers/FindRouteAroundBarriersView.Model.swift
Shared/Samples/Find route in mobile map package/FindRouteInMobileMapPackageView.Models.swift
Shared/Samples/Find route in transport network/FindRouteInTransportNetworkView.Model.swift
Shared/Samples/Geocode offline/GeocodeOfflineView.Model.swift
Shared/Samples/Render multilayer symbols/RenderMultilayerSymbolsView.swift
Shared/Samples/Show service area/ShowServiceAreaView.swift
Shared/Samples/Style point with picture marker symbols/StylePointWithPictureMarkerSymbolsView.swift

Upgrades the project format from Xcode 13 to Xcode 15 (our minimum). Also, verified project settings (using Xcode 15.0) and set the recommended project settings, updating relevant areas of the code based on the new settings.

[Setup] Upgrade project format

---

README.md
Samples.xcodeproj/project.pbxproj

This PR bumps the samples and toolkit version numbers to 200.5.0. 
```sh
grep -nrF '200.4' .
```

[Update] Bump version numbers for 200.5.0

---

Samples.xcodeproj/project.pbxproj

This PR adds one missing file to the copy phase.

[Fix] Add missing file to the Copy Source Code Files phase

---

Shared/Samples/Show grid/ShowGridView.swift

This PR fixes a bug a in the `Show grid` sample where some of the grid settings wouldn't save state in between the sheet being closed and reopened. To avoid setting state in the view's init, I moved the state variables to a model. I tired to change it as little as possible so there should be no behavior changes besides the bug fix.
- `swift/issues/5774`
- Ensure different combinations of gird settings persist in between the sheet being closed.

[Fix] `Show grid` grid settings

---

Shared/Samples/Add ENC exchange set/AddENCExchangeSetView.swift
Shared/Samples/Add raster from service/AddRasterFromServiceView.swift
Shared/Samples/Analyze network with subnetwork trace/AnalyzeNetworkWithSubnetworkTraceView.swift
Shared/Samples/Animate 3D graphic/Animate3DGraphicView.Model.swift
Shared/Samples/Animate 3D graphic/Animate3DGraphicView.swift
Shared/Samples/Apply mosaic rule to rasters/ApplyMosaicRuleToRastersView.swift
Shared/Samples/Create load report/CreateLoadReportView.swift
Shared/Samples/Display dimensions/DisplayDimensionsView.swift
Shared/Samples/Edit and sync features with feature service/EditAndSyncFeaturesWithFeatureServiceView.swift
Shared/Samples/Find closest facility from point/FindClosestFacilityFromPointView.swift
Shared/Samples/Find route around barriers/FindRouteAroundBarriersView.swift
Shared/Samples/Monitor changes to draw status/MonitorChangesToDrawStatusView.swift
Shared/Samples/Play KML tour/PlayKMLTourView.swift
Shared/Samples/Query features with Arcade expression/QueryFeaturesWithArcadeExpressionView.swift
Shared/Samples/Query related features/QueryRelatedFeaturesView.swift
Shared/Samples/Run valve isolation trace/RunValveIsolationTraceView.swift
Shared/Samples/Set feature request mode/SetFeatureRequestModeView.swift
Shared/Samples/Show scale bar/ShowScaleBarView.swift
Shared/Samples/Show utility associations/ShowUtilityAssociationsView.swift
Shared/Samples/Show viewshed from point on map/ShowViewshedFromPointOnMapView.swift
Shared/Samples/Style point with distance composite scene symbol/StylePointWithDistanceCompositeSceneSymbolView.swift
Shared/Samples/Trace utility network/TraceUtilityNetworkView.swift
Shared/Samples/Validate utility network topology/ValidateUtilityNetworkTopologyView.swift
Shared/Supporting Files/Views/AboutView.swift

This PR removes the usage of the following deprecated APIs:
- [Section.init(header:content:)](https://developer.apple.com/documentation/swiftui/section/init(header:content:)) & [Section.init(footer:content:)](https://developer.apple.com/documentation/swiftui/section/init(footer:content:))
- [String.init(contentsoffile:)](https://developer.apple.com/documentation/swift/string/init(contentsoffile:))
- [View.cornerRadius(_:antialiased:)](https://developer.apple.com/documentation/swiftui/view/cornerradius(_:antialiased:))
Closes #506
Ensure the project builds as expected (this current requires toolkit daily).

[Update] Remove deprecated API usage

---

Shared/Samples/Add features with contingent values/AddFeaturesWithContingentValuesView.swift

This PR fixes a bug in `Add features with contingent values` where the popover would not show up on iPadOS 18. This involved:
- Specifying an `arrowEdge`.
- Replacing the `ZStack` with an `overlay` so that the popover still works on Mac Catalyst.
All other changes are just white space. There should be no UI changes.
- `swift/issues/6311`
- Ensure that a popover is presented when the map is tapped on iPadOS 18.

[Fix] `Add features with contingent values` popover

---

.swiftlint.yml
Shared/Samples/Animate 3D graphic/Animate3DGraphicView.Model.swift
Shared/Samples/Densify and generalize geometry/DensifyAndGeneralizeGeometryView.swift
Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.Model.swift
Shared/Samples/Style symbols from mobile style file/StyleSymbolsFromMobileStyleFileView.swift

This PR updates the Swift Lint `opt_in_rules`:
- Removes some that are now [default rules](https://realm.github.io/SwiftLint/rule-directory.html).
- Adds some that are present in the Swift API but were missing here.
Ensure the project builds without warnings.

[Update] Swift Lint opt-in rules

---

Shared/Samples/Edit features using feature forms/EditFeaturesUsingFeatureFormsView.swift

This PR updates `Edit features using feature forms` to use the new `FeatureForm.hasEdit` property. Tapping the map or the discard button now only presents the discard edits alert if the feature form has edits.
- `apollo/issues/880`
- Add `swift-toolkit-daily`. 
- Tap on a feature in the sample.
- Trying closing the form both with and without edits.

[Update] Use `FeatureForm.hasEdits`

---

README.md
Shared/Samples/Set spatial reference/SetSpatialReferenceView.swift
Shared/Supporting Files/Views/AboutView.swift

This PR updates the dates from `2024` -> `2025` and fixes a few other minor issues I found while working on the samples.
- Ensure the project still builds.

[Update] 2024 -> 2025

---

Shared/Samples/Query map image sublayer/QueryMapImageSublayerView.swift

This PR fixes a Xcode 16.2 build error introduced in #631.

[Fix] Task group build error

---

Shared/Samples/Set basemap/README.md
Shared/Samples/Set basemap/README.metadata.json

This PR updates `Set basemap` in `Maps` category.
- `common-samples/pull/3989`
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/614#issuecomment-2884667796

[Update] README and metadata for Set basemap

---

Shared/Supporting Files/Extensions/EnvironmentValues+RequestReviewModel.swift

- `swift/issues/6970`
Build with both Xcode 16.0 and 16.4 and verify that there are no build errors.

[Fix] Fix build failure using Xcode 16.0

---

Shared/Samples/Set map image layer sublayer visibility/README.md

[Fix] Fixes broken image file path in README

---

Shared/Samples/Display content of utility network container/DisplayContentOfUtilityNetworkContainerView.Model.swift
Shared/Samples/Find route in mobile map package/FindRouteInMobileMapPackageView.Models.swift
Shared/Samples/Show device location with NMEA data sources/FileNMEASentenceReader.swift

This PR fixes the current documentation warnings in the Samples.
Build the documentation and ensure there are no warnings.

[Fix] Documentation warnings

---

Shared/Samples/Add integrated mesh layer/AddIntegratedMeshLayerView.swift
Shared/Samples/Add raster from service/AddRasterFromServiceView.swift
Shared/Samples/Analyze network with subnetwork trace/AnalyzeNetworkWithSubnetworkTraceView.Model.swift
Shared/Samples/Apply mosaic rule to rasters/ApplyMosaicRuleToRastersView.swift
Shared/Samples/Create and save map/CreateAndSaveMapView.swift
Shared/Samples/Create load report/CreateLoadReportView.Model.swift
Shared/Samples/Find closest facility from point/FindClosestFacilityFromPointView.swift
Shared/Samples/Find route around barriers/FindRouteAroundBarriersView.swift
Shared/Samples/Generate geodatabase replica from feature service/GenerateGeodatabaseReplicaFromFeatureServiceView.swift
Shared/Samples/Query related features/QueryRelatedFeaturesView.swift
Shared/Samples/Query table statistics group and sort/QueryTableStatisticsGroupAndSortView.swift
Shared/Samples/Run valve isolation trace/RunValveIsolationTraceView.swift
Shared/Samples/Show device location using indoor positioning/ShowDeviceLocationUsingIndoorPositioningView.swift
Shared/Samples/Show service areas for multiple facilities/ShowServiceAreasForMultipleFacilitiesView.swift
Shared/Samples/Show viewshed from point on map/ShowViewshedFromPointOnMapView.swift
Shared/Samples/Trace utility network/TraceUtilityNetworkView.swift

This PR removes the ellipses from the string literals displayed with a `ProgressView` in response to  https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/678#pullrequestreview-3056436374.
Closes #680

[Update] Remove Progress View ellipses

---

Shared/Samples/Augment reality to navigate route/README.md

Rewording documentation - related issue: [#448](https://github.com/Esri/arcgis-maps-sdk-swift-samples/issues/448)

[Fix] update documentation to clarify

---

Shared/Supporting Files/Views/FavoritesView.swift

This PR fixes a bug where moving and deleting favorite samples wouldn't always work when the User Defaults contained invalid values, such as the name of a sample that was added in another branch.
- Open a simulator.
- Run the following command to open the simulator's User Defaults:
```
open $(xcrun simctl get_app_container booted com.esri.arcgis-swift-sdk-samples data)/Library/Preferences/com.esri.arcgis-swift-sdk-samples.plist
```
- Add invalid sample names to the `favoriteSampleNames` key's value such as:
```
["test", "Display map", "test", "Geocode offline", "test", "Manage features", "test"]
```
- Run the Samples app.
- Ensure that the favorites can be moved and deleted as expected.
|Before|After|
|:-:|:-:|
| ![Simulator Screen Recording - 1 - iPhone 16 Pro - 2025-08-14 at 09 45 …

[Fix] Favorites move and delete

---

Shared/Samples/Create and edit geometries/README.metadata.json
Shared/Samples/Show geodesic path between two points/README.metadata.json

This PR updates some categories that were changed in the common designs.
- `common-samples/pull/4014`

[Update] Some categories
