Shared/Samples/Project geometry/README.md, Shared/Samples/Project geometry/README.metadata.json
This PR fixes the path to the screenshot. Thanks @maryharvey !
preview: https://github.com/Esri/arcgis-maps-sdk-swift-samples/blob/Ting/Fix-Screenshot/Shared/Samples/Project%20geometry/README.md
=> [Fix] Screenshot path for `Project geometry`

Shared/Samples/Generate offline map/GenerateOfflineMapView.swift, Shared/Samples/Generate offline map/README.md
This PR fixes `Generate offline map` to avoid 2 instances of a map. Please refer to the issues below for more details. Thanks @sbiswas96 !
- `common-samples/issues/3808`
- `waverley/issues/2500`
- https://github.com/Esri/arcgis-runtime-samples-qt/pull/1553
- Sample still behaves the same
- README reads correctly
=> [Fix] `OfflineMapTask` instantiation pattern

Shared/Samples/Set surface placement mode/SetSurfacePlacementModeView.swift, Shared/Samples/Show device location/ShowDeviceLocationView.swift
This PR fixes a binary framework only issue. See Zach's comment here: https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/101#pullrequestreview-1214446015
See: https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/214
Build with binary framework and it doesn't show more unknown default warnings.
=> [Fix] `@unknown default` warnings

README.md, Samples.xcodeproj/project.pbxproj, Shared/Supporting Files/Views/AboutView.swift
This PR adds Swift package instructions and changes the project to use the GitHub repo SP instead of local package.
As the https://github.com/Esri/arcgis-maps-sdk-swift package isn't public yet, you cannot build the project.
- Either test with the local packages by dragging in the toolkit and ArcGIS folder
- Or quickly test after the new SDK is released and report any issue it might cause
- Or use commit [f926975](https://github.com/Esri/arcgis-maps-sdk-swift/pull/2/commits/f92697566858be47b869d69e1be7fb8ff16480b9) if you know what you are doing, with https://github.com/Esri/arcgis-maps-sdk-swift/pull/2 😉
=> [Update] Add Swift package instructions

Shared/Samples/Add feature layers/AddFeatureLayersView.swift, Shared/Samples/Add raster from file/AddRasterFromFileView.swift, Shared/Samples/Add scene layer from service/AddSceneLayerFromServiceView.swift, Shared/Samples/Browse building floors/BrowseBuildingFloorsView.swift, Shared/Samples/Clip geometry/ClipGeometryView.swift, Shared/Samples/Create planar and geodetic buffers/CreatePlanarAndGeodeticBuffersView.swift, Shared/Samples/Cut geometry/CutGeometryView.swift, Shared/Samples/Display map from mobile map package/DisplayMapFromMobileMapPackageView.swift, Shared/Samples/Display map/DisplayMapView.swift, Shared/Samples/Display overview map/DisplayOverviewMapView.swift, Shared/Samples/Display scene/DisplaySceneView.swift, Shared/Samples/Download vector tiles to local cache/DownloadVectorTilesToLocalCacheView.swift, Shared/Samples/Find route/FindRouteView.swift, Shared/Samples/Generate offline map/GenerateOfflineMapView.swift, Shared/Samples/Project geometry/ProjectGeometryView.swift, Shared/Samples/Search with geocode/SearchWithGeocodeView.swift, Shared/Samples/Select features in feature layer/SelectFeaturesInFeatureLayerView.swift, Shared/Samples/Set basemap/SetBasemapView.swift, Shared/Samples/Set surface placement mode/SetSurfacePlacementModeView.swift, Shared/Samples/Set viewpoint rotation/SetViewpointRotationView.swift, Shared/Samples/Show callout/ShowCalloutView.swift, Shared/Samples/Show device location/ShowDeviceLocationView.swift, Shared/Samples/Show result of spatial operations/ShowResultOfSpatialOperationsView.swift, Shared/Samples/Show result of spatial relationships/ShowResultOfSpatialRelationshipsView.swift, Shared/Samples/Show viewshed from point in scene/ShowViewshedFromPointInSceneView.Model.swift, Shared/Samples/Style graphics with renderer/StyleGraphicsWithRendererView.swift, Shared/Samples/Style graphics with symbols/StyleGraphicsWithSymbolsView.swift
This PR changes the `@StateObject` pattern in most of the samples, to use an observable model object to manage the data.
- `swift/issues/3271`
- `swift/issues/3250`
- https://github.com/ArcGIS/arcgis-maps-sdk-swift-toolkit/issues/200
- Potentially #48 and #89 
To run the app, you'll need to
1. replace the toolkit dependency line in Package.swift locally with `.package(name: "arcgis-maps-sdk-swift", path: "../swift/ArcGIS")`.
2. drag the toolkit into the samples project, so it overrides the remote resolved packages and uses the local toolkit repo instead.
No behavioral change should present. Verify all changed sample to work as expected.
- What should be a good generic docstring for the view model objects?
=> [Update] Use model to manage geo view and data

iOS/Info.plist
This PR fixes an issue in the `Info.plist`. In beta the version was hardcoded for unknown reason. With this change, the bundle version will be the build number, which shows such as 200.0.0 (3456) instead of 200.0.0 (1).
=> [Fix] Version variable in Info.plist

Shared/Samples/Add raster from file/AddRasterFromFileView.swift, Shared/Samples/Add scene layer from service/AddSceneLayerFromServiceView.swift, Shared/Samples/Browse building floors/BrowseBuildingFloorsView.swift, Shared/Samples/Display map/DisplayMapView.swift, Shared/Samples/Display overview map/DisplayOverviewMapView.swift, Shared/Samples/Display scene/DisplaySceneView.swift, Shared/Samples/Set basemap/SetBasemapView.swift, Shared/Samples/Set viewpoint rotation/SetViewpointRotationView.swift, Shared/Samples/Show callout/ShowCalloutView.swift
Close #123 .
In the swift repo there was a discussion on whether to use `StateObject` and view model pattern , or simply `State`, for a geo model (map and scene). In the end we concluded for the simpler samples that don't have extra data flow, `State` is preferred.
This PR changed all the samples which the view model only holds 1 property which is the geo model.
- `swift/pull/3698`
- `native-apis-doc/issues/3636`
Run all changed samples and see if they behave the same.
cc @sbaskaran
=> [Update] Simplify view model pattern when it is not needed

Samples.xcodeproj/project.pbxproj
The source files for "Change map view background" weren't copied, causing a crash when the info button is pressed.
- Note: The info pane seems to be broken on simulators but works fine on my physical iPad.
=> [Fix] Change map view background info button

Shared/Samples/Change viewpoint/ChangeViewpointView.swift
Use of `setViewpoint` methods needs to be updated since they are now non-throwing due to `swift/pull/3838`.
=> [Update] Use updated `setViewpoint` methods

Shared/Samples/Set viewpoint rotation/SetViewpointRotationView.swift
This PR updates `Set viewpoint rotation`.
The autohide setting is now a view modifier.
- https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/291
The sample behaves exactly the same as before.
To match the old code, should we explicitly write `.autoHideDisabled(true)`? I don't think so because…
1. its default value is true (which means the compass doesn't autohide)
2. there are other view modifiers on the compass. A user can explore them with other methods, while the sample can keep simple.
=> [Update] Adjust `Compass` API signature

Shared/Samples/Sketch on map/SketchOnMapView.swift
Closes #158 
- Disables "Delete selected element" when the selected element cannot be deleted.
=> [Fix] Deletion precondition in Sketch on map

Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.Model.swift
ting: See Swift 3906 - it involves a bug in Item.ID's optionality, and the final solution is hard to explain in a few words.
=> [Fix] Compile error related to `Item.id`

Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.swift, Shared/Samples/Change map view background/ChangeMapViewBackgroundView.swift
This PR fixes the bug where the settings sheet in some samples is getting anchored in the wrong position. Before, the sheet modifier was called on the geo view and SwiftUI defaulted to having the popover attachment anchor below the geo view. With these changes that call the view modifier on the settings button itself, SwiftUI defaults to the expected behavior which anchors the popover above the settings button.
- `swift/issues/3879`
=> [Fix] Settings sheet in some samples

.github/PULL_REQUEST_TEMPLATE.md
Please see the discussion here: https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/172#discussion_r1170549693 
The template was accidentally removed in a new sample PR. This PR adds it back to `main`.
Ref: #9
=> [Setup] Add back PULL_REQUEST_TEMPLATE.md

Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.MapPicker.swift
This PR replaces 2 iCloud SF Symbols. Per Apple Use Restrictions
> This symbol may not be modified and may only be used to refer to Apple’s iCloud service.
=> [Update] Get rid of iCloud SF Symbols usage

Shared/Supporting Files/Views/AboutView.swift
This PR fixes the info button crash when developing using a local source code package. 
- #157 
1. Build without changing the project file. It resolves to the 200.1 released binary package
2. Build after changing the project file to use the local source package.
3. Tap on info button and no crash.
4. You can also test build with swift-daily.
=> [Setup] Fix local bundle ID caused crash

README.md
See https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/318
> It might be best if both the toolkit and the samples app update their minimum Xcode version to 14.1, the first version to include the macOS 13 SDK.
Another PR will fix this on v.next #197
=> [Fix] Bump requirement to Xcode 14.1.

Shared/Supporting Files/Models/OnDemandResource.swift
This PR fixes the ODR resource force unwrap not found problem described in #48 
- `swift/issues/4199`
1. Do a fresh install and fresh build
2. When the samples app first open, check an arbitrary sample that has ODR, e.g. 
- [Add raster from file](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/main/Shared/Samples/Add%20raster%20from%20file)
- [Add feature layers](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/main/Shared/Samples/Add%20feature%20layers)
- Change camera controller
- [Display map from mobile map package](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/main/Shared/Samples/Display%20map%20from%20mobile%20map%20package)
3. Make sure none of them crashes
I haven't been able to reproduce a crash with this fix. My gut says the root cause was that …
=> [Fix] Change on-demand resources downloaded state criteria

Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.Model.swift, Shared/Samples/Change map view background/ChangeMapViewBackgroundView.Model.swift, Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.Model.swift
This PR removes extra `import SwiftUI` for data models. Close the card https://github.com/Esri/arcgis-maps-sdk-swift-samples/projects/1#card-89559142
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/projects/1#card-89559142
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/203#discussion_r1242904166
All affected samples still compile.
=> [Update] Examine SwiftUI importation

Scripts/GenerateSampleViewSourceCode.swift, Shared/Supporting Files/Models/Sample.swift
This PR updates the script that generates the `Sample` struct from metadata…
- it exit with error code 1 "Command RuleScriptExecution failed with a nonzero exit code" when a malformatted JSON is encountered, instead of ignoring it, so it is easier for a developer to locate the mistake
- it includes the category from the metadata so we can implement the UI
- `swift/issues/4227`
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/projects/1#card-89299131
- Mess up a metadata in any sample
- See if the build script exit with error
- Fix the metadata, clean build folder
- Build again and the error is gone
- You can try to print out the category of a sample somewhere
=> [Setup] Improve error handling and add category to metadata script 

Scripts/GenerateSampleViewSourceCode.swift
This PR fixes an issue in the decoder script. When Git switches branches, it sometimes leaves an empty directory behind. When the script is run, it cannot find the metadata file at the path and prints a "sample couldn’t be decoded." error.
This PR fixes it by returning `nil` for non-existing metadata.
Thanks @CalebRas for reporting this bug!
Create an empty folder in the `Samples` folder, and the project still builds.
=> [Fix] Sample metadata decoding script works incorrectly with empty directory

Samples.xcodeproj/project.pbxproj, Shared/Samples/Create convex hull around geometries/README.metadata.json, Shared/Samples/Search with geocode/README.metadata.json, Shared/Samples/Set up location-driven geotriggers/README.metadata.json, Shared/Samples/Show result of spatial operations/README.metadata.json
This PR updates the "category" in the metadata file to match the [Kotlin samples](https://github.com/Esri/arcgis-maps-sdk-kotlin-samples) and the [new common design sample categories](https://devtopia.esri.com/runtime/common-samples/blob/main/designs/categories.md) for the last batch of the swift samples. 
- `swift/issues/4227`
* Verify each sample category matches the corresponding Kotlin sample and/or the correct common design sample category.
=> [Update] Sample categories - third batch

Shared/Samples/Create buffers around points/CreateBuffersAroundPointsView.swift
Close #212. This PR updates `Create buffers around points` added in #185 .
- #212 
The sample should behave the same as before.
In hindsight I should have paid more attention to the code review. This sample was one of Caleb's first samples so I let it go without being too harsh.
Ideally we should have a more careful mindset on how to use the data model object. Try to avoid the case where the model knows about states in the UI, or in other words, UI states should be derived from the model, not reverse.
=> [Update] Refactor `CreateBuffersAroundPointsView.Model`

Shared/Supporting Files/Views/CategoryGridView.swift, Shared/Supporting Files/Views/ContentView.swift
Fixes issue described [here](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/221#issuecomment-1641069920), where going back from a sample takes the user all the way back to the Categories view, not the view for the category to which the sample belongs. This also means that when the categories are displayed in a sidebar, tapping on a category opens that category in the sidebar, which is expected behavior for this kind of a navigation setup on iOS.
=> [Fix] Issue with sidebar navigation

Shared/Supporting Files/Views/CategoryGridView.swift
This PR implements a fix to the Sample Viewer by centering category title text on the category grid tiles. Initially, text was aligned left when there were multiple lines.
- Load the Sample Viewer on iPad and verify the text is centered on the category grid titles.
- Verify the app works the same otherwise. 
|Before|After|
|:-:|:-:|
|![iPad Screen Shot, Before](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/f6c556ab-af04-45a5-8b1a-0ed4d2b119f0)|![iPad Screen Shot, After](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/356d2025-cc17-408e-9e2b-e9387ff1260b)|
=> [Fix] Center category grid text

Shared/Supporting Files/Views/SampleListView.swift
The crash is due to `OnDemandResource` state being re-used across samples, a problem described in the [Initialize state objects using external data](https://developer.apple.com/documentation/swiftui/stateobject#Initialize-state-objects-using-external-data) section of the `StateObject` doc:
> SwiftUI only initializes a state object the first time you call its initializer in a given view. This ensures that the object provides stable storage even as the view’s inputs change. However, it might result in unexpected behavior or unwanted side effects if you explicitly initialize the state object.
The solution is described in the [Force reinitialization by changing view identity](https://developer.apple.com/documentation/swiftui/stateobject#Force-reinitialization-by-changing-view-identity) …
=> [Fix] ODR-related crash

Shared/Samples/Analyze network with subnetwork trace/AnalyzeNetworkWithSubnetworkTraceView.swift
List items can now be selected by clicking anywhere in the cell. Before only the cell text was selectable. This PR also has a bug fix to reset previous textfield input. 
- `swift/issues/4402`
Add condition by selecting the attribute, comparison, and value. Make sure that list item can be selected by clicking anywhere in the cell. 
I tried to use a Button to avoid use of `.onTapGesture` but the UI had a few issues including incorrect accent color and line separator style, so I decided to use the original implementation:
=> [Fix] Clicking anywhere on the cell is not working in Analyze network with subnetwork trace sample

Shared/Samples/Query feature table/QueryFeatureTableView.swift, Shared/Samples/Show line of sight between points/ShowLineOfSightBetweenPointsView.swift
This PR removes unneeded imports.
Make sure the app builds with these changes.
=> [Fix] Remove unneeded `import ArcGISToolkit`

.swiftlint.yml
The rule [has been deprecated](https://github.com/realm/SwiftLint/releases/tag/0.50.0) and now produces a warning:
=> [Setup] Remove `anyobject_protocol` rule

.swiftlint.yml
This PR opts out a linter rule that was introduced in SwiftLint 0.52.0. When I upgraded to the latest version 0.52.4, I saw these warnings with the attributes with argument, such as
```swift
// current
@Environment(\.dismiss) private var dismiss: DismissAction
// linter suggested
@Environment(\.dismiss)
private var dismiss: DismissAction
```
My preference is to still keep them on the same line, because even if they have arguments, they annotate a variable nonetheless; in contrast to sth like `@MainActor` that annotates a type, which I'm OK with putting on the line above.
- https://realm.github.io/SwiftLint/attributes.html
- https://github.com/realm/SwiftLint/issues/4843
- https://github.com/realm/SwiftLint/pull/4855
- https://github.com/realm/SwiftLint/tree/0.52.0
1. Upgrade `SwiftLint` …
=> [Fix] Configure the attribute linter rule to exclude some cases

Shared/Samples/Analyze network with subnetwork trace/AnalyzeNetworkWithSubnetworkTraceView.Model.swift
This PR fixes an unknown default warning using the swift-toolkit-daily package.
- Build using binary won't have warning
- Build using source code will show a warning
- https://github.com/apple/swift-evolution/blob/main/proposals/0192-non-exhaustive-enums.md
- https://forums.swift.org/t/handling-future-cases-of-enums-in-libraries-without-binary-stability-concerns/32026/11
=> [Fix] Add unknown default for binary dependency

Samples.xcodeproj/project.pbxproj
Xcode automatically makes this change whenever the project file is saved.
=> [Fix] Xcode project file

README.md, Samples.xcodeproj/project.pbxproj
This PR bumps the version number to 200.2.
=> [Update] Bump version number for 200.2.0

Shared/Samples/Trace utility network/TraceUtilityNetworkView.Model.swift, Shared/Samples/Trace utility network/TraceUtilityNetworkView.Views.swift
This PR
- Add a status message for potentially failed/nil method
- Fix the UI on iOS 17 for bottom bar. It is defaulted to the left edge without spacers.
- `swift/issues/4401`
Run the sample on iOS 17 beta, UI looks good.
=> [Fix] Add status message and fix UI for `Trace utility network`

Shared/Samples/Display points using clustering feature reduction/DisplayPointsUsingClusteringFeatureReductionView.swift, Shared/Samples/Set up location-driven geotriggers/SetUpLocationDrivenGeotriggersView.swift, Shared/Samples/Show popup/ShowPopupView.swift
This PR updates usage of the Floating Panel across three samples in response to changes in [Toolkit #404](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/404)
Test the 3 changed samples on Catalyst, iPhone and iPad.
=> [Update] Floating Panel usage

Shared/Supporting Files/Views/SampleRow.swift
Fixes a bug in iOS 16+ where the help text and accessory button are not clearly visible when the list item selection color is the accent color (purple/pink) instead of grey. This PR adds opacity to the help text so that the system sets the text color. The accessory button is now a label with an icon and tap gesture rather than a Button since the system will set the color automatically.
- `swift/issues/3878`
- Test on iPhone and iPad on iOS 16 and iOS 17
Before:
After:
=> [Fix] accessory button and help text color is not clearly visible

Shared/Samples/Analyze network with subnetwork trace/AnalyzeNetworkWithSubnetworkTraceView.Model.swift, Shared/Samples/Create load report/CreateLoadReportView.Model.swift, Shared/Samples/Set up location-driven geotriggers/SetUpLocationDrivenGeotriggersView.Model.swift, Shared/Samples/Set visibility of subtype sublayer/SetVisibilityOfSubtypeSublayerView.Model.swift
This PR fixes extraneous `import SwiftUI` in data model swift files.
- https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/410
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/projects/1#card-89559142
Build and run the app, and it still behaves the same.
=> [Fix] Only `import Combine` for needed types

Shared/SamplesApp.swift, Shared/Supporting Files/Views/SampleDetailView.swift
This PR allows the samples with dependent data files to run on Mac Catalyst.
- `swift/issues/4354`
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/93#issuecomment-1339643112
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/projects/1#card-87094498
- Build and run the app on Mac Catalyst
- You'll see the samples that use offline data, such as mobile map package and feature layer samples
- You can open these samples on Mac Catalyst without crashing
- Build and run on iOS
- The samples still download using the ODR API
I was surprised to find that Apple provides native support for using those ODR-on-iOS directly on Mac Catalyst, without a custom copy files or copy bundle resources phase in the build phases. I was under the impression that all files with ODR tag are **not** …
=> [Update] Allow bundle resources on Mac Catalyst

Shared/Samples/Trace utility network/TraceUtilityNetworkView.Model.swift
This PR fixes an issue in the `Trace utility network` sample.
In the original PR, when the sample opens, a computed property `private var network: UtilityNetwork? { map.utilityNetworks.first }` tries to get the first utility network from the web map. However, because the web map is not explicitly loaded, `network` can become `nil` occasionally, depending on the load timing of the map.
This leads to the problem in 4401 where the `network?.makeElement(arcGISFeature: feature)` call silently fails. A status message was added in #248 to show the error.
After discussing with Jen, both the web map and the network need to be loaded. Only loading the map is not enough; only loading the network doesn't guarantee the map to be present either. Once the map is loaded, we can safely assume the utility …
=> [Fix] "false" utility network load problem

Shared/Supporting Files/Views/SampleInfoView.swift
This PR adjusts the info view's control position and size.
- Add an ideal width to the segmented picker so it's width doesn't differ among iOS versions
- Add spacer to bottom bar to make the code picker centered
See `swift/issues/4377`.
Build and run on iOS 16/17 iPad.
- Ideally, we don't apply the fixed width frame modifier to the segmented picker. But that would cause the width problem described in issue 4377.
- Another idea is to use `fixedSize()` modifier to make the segmented control tight. While it is commonly seen on iPhone, it is generally wider on iPad and Mac.
- Please share your thoughts on which looks better:
- segmented picker: tight / fixed width (current) / fill the top bar (original, with bug on iOS 17)
- code picker: centered (current) / aligned to the right / system …
=> [Update] Adjust info view control size

Shared/Samples/Monitor changes to map load status/README.md
This PR implements a fix to the `Monitor changes to map load status` [README](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/v.next/Shared/Samples/Monitor%20changes%20to%20map%20load%20status) since the image was not loading correctly due to a typo the image path. `main` is also being updated by #270.
- Ensure the image loads correcting on the [README](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/Fix-MonitorMapLoadStatusReadME/Shared/Samples/Monitor%20changes%20to%20map%20load%20status) and that every thing else remains unchanged.
|Before|After|
|:-:|:-:|
|![Screenshot 2023-09-21 at 10 10 43 AM](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/9828a471-df87-4f5a-b817-051e7dd0f6b0)|![Screenshot 2023-09-21 at 10 10 38 …
=> [Fix] Monitor changes to map load status README image path typo

Shared/Samples/Monitor changes to map load status/README.md
I was browsing the site earlier today and noticed the image at this path was not displaying:
https://developers.arcgis.com/swift/sample-code/monitor-changes-to-map-load-status/
A simple correction to the image's referenced filename appears to do the trick.
n/a
|Before|After|
|:-:|:-:|
| ![image](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/25207711/52745d9c-69fd-43b2-acf2-af8660b4c576) | ![image](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/25207711/7c366b43-9371-4b40-af47-0186f7446291) |
=> [Fix] Update README.md to correct image path typo

Shared/Samples/Add feature layers/README.md
This PR adds trailing spaces within each step in the **How it works** section of the `Add feature layers` sample README to ensure sub-list items exist on new lines.
For example, compare:
- **Swift** - https://developers.arcgis.com/swift/sample-code/add-feature-layers/#how-it-works
- **Kotlin** - https://developers.arcgis.com/kotlin/sample-code/add-feature-layers/#how-it-works
n/a - quick fix
|Before|After|
|:-:|:-:|
| ![image](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/25207711/72bcedf6-0c02-46ab-aa81-92b27f5ef22c) | ![image](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/25207711/b427bda2-f60d-414d-b32c-c06279d3c9eb) |
=> Ensure new line for sub-lists

Samples.xcodeproj/project.pbxproj
This PR implements a fix to the `Group layers together` and `Add custom dynamic entity data source` samples by adding their source code files that were missing from the `Build Phases` -> `Copy Source Code Files`.
-  N\A, quick fix
- Verify the code additional code files come up by going to info button -> "Code" -> filename for each sample.
|Before|After|
|:-:|:-:|
|![Group layers together - before](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/390f5d53-02d7-4b04-acf9-174f3c1208db)|![Group layers together - after](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/31606633-06a9-4631-8263-a21b34d3e623)|
|Before|After|
|:-:|:-:|
|![Add custom dynamic entity data source - before](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/6c …
=> [Fix] Add missing source code files to Build Phases

Shared/Supporting Files/Views/ContentView.swift
This PR implements a fix to bugs that would come from nested `NavigationLink`s (e.g. using one in the top view of a sample) on iOS 16+ on both iPad and iPhone.
- `swift/issues/NA` (quick fix)
- Ensure the navigating through the Sample Viewer is same.
=> [Fix] Sample Viewer navigation bug

Shared/Samples/Identify raster cell/IdentifyRasterCellView.swift
This PR fixes `Identify raster` in `Layer` category.
The cancellation error thrown by the identify operation is ignored so the error alert doesn't constantly pop up.
- `swift/issues/4793`
Long tap and drag on the map. With the fixes there shouldn't be a cancellation error alert.
=> [Fix] Handle cancellation error in Identify raster

Shared/Samples/Animate 3D graphic/Animate3DGraphicView.swift, Shared/Samples/Display dimensions/DisplayDimensionsView.swift, Shared/Samples/Identify KML features/IdentifyKMLFeaturesView.swift, Shared/Samples/Show mobile map package expiration date/ShowMobileMapPackageExpirationDateView.swift
This PR makes a few colors dark mode adaptive.
- `swift/issues/4792`
Go to the 4 changed samples and cmd + shift + A to switch between light and dark mode.
=> [Fix] Fix non-adaptive colors in samples

Shared/Samples/Create and edit geometries/CreateAndEditGeometriesView.swift
This PR fixes `Create and edit geometries` in `Maps` category.
- `swift/issues/4794`
Create a geometry with uniform mode. Create another geometry with the toggle checked. It should still preserve the aspect ratio.
=> [Fix] Geometry editor scale mode issue

Shared/Supporting Files/Extensions/View+Sheet.swift
This PR implements fixes to the following bugs that would occur when using the custom sheet modifier in the sample viewer:
1. If there was more than one custom sheet within a given view, some of the sheets would auto-dismiss upon opening, e.g. a sample containing settings sheet would cause the info sheet to auto-dismiss when opened.
2. Whenever a custom sheet was closed, `Modifying state during view update, this will cause undefined behavior.` would be thrown. 
3. Custom sheets dismissed using the `DismissAction` from the `Environment` wouldn't always re-present.
URL to custom sheet modifier file: [View+Sheet.swift](https://github.com/Esri/arcgis-maps-sdk-swift-samples/blob/Caleb/Fix-SheetExtensionAutoDismiss/Shared/Supporting%20Files/Extensions/View%2BSheet.swift)
- `swift/issues/4778` …
=> [Fix] Custom sheet auto dismiss

Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.SettingsView.swift, Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.swift, Shared/Samples/Change map view background/ChangeMapViewBackgroundView.SettingsView.swift, Shared/Samples/Change map view background/ChangeMapViewBackgroundView.swift, Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.MapPicker.swift, Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.swift, Shared/Samples/Find route around barriers/FindRouteAroundBarriersView.Views.swift, Shared/Samples/Find route around barriers/FindRouteAroundBarriersView.swift, Shared/Samples/Geocode offline/GeocodeOfflineView.swift, Shared/Samples/Show viewshed from point in scene/ShowViewshedFromPointInSceneView.ViewshedSettingsView.swift, Shared/Samples/Show viewshed from point in scene/ShowViewshedFromPointInSceneView.swift, Shared/Samples/Trace utility network/TraceUtilityNetworkView.swift
This PR replaces the use of the `EnvironmentObject` with `ObservedObject` in the samples since the ones that were using it just passed their view model down to a single child view.
- #137 
- `swift/issues/4843`
- Ensure the affected samples work as expected.
=> [Update] Replace EnvironmentObject with ObservedObject in samples

Shared/Samples/Download vector tiles to local cache/DownloadVectorTilesToLocalCacheView.swift, Shared/Samples/Generate offline map/GenerateOfflineMapView.swift
This PR sets `minScale` on 2 samples to disallow the map to zoom too far and thus download too much data.
- #121 
- Run the samples, make sure they can still export/generate files correctly.
It seems that the generate offline map sample has some issue with generated data. See below for details. They are not affected by the changes in this PR.
- swift/issues/2008
- #261
=> [Update] Set min scale on maps to avoid huge download

Shared/SamplesApp.swift, Shared/Supporting Files/Views/CategoriesView.swift, Shared/Supporting Files/Views/ContentView.swift, Shared/Supporting Files/Views/FavoritesView.swift, Shared/Supporting Files/Views/SamplesSearchView.swift, Shared/Supporting Files/Views/Sidebar.swift
This PR updates how the list of samples is accessed by views within the Sample Viewer. Before, the list was passed down from `SamplesApp` as a parameter to the subsequent child views until it was eventually used. Those parameters were removed, and now, the views that need the list of samples access it through the static variable, ` SamplesApp.samples`.
- `swift/issues/4842`
- Ensure the Sample Viewer works the same as before, particularly the categories, favorites, and searching.
=> [Update] Samples list accessing

Shared/Samples/Download vector tiles to local cache/DownloadVectorTilesToLocalCacheView.swift
This PR refactors `DownloadVectorTilesToLocalCacheView`. Close #114 
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/107#discussion_r1091301687
- #114 
- Run the sample and ensure the vector tiles download still works.
- Use Network Link Conditioner or other ways to emulate these scenarios
- The basemap loads too slowly, so the `exportVectorTilesTask` is `nil`
- The `exportVectorTilesTask` loads too slowly, so its load status is not `loaded`
- In both cases, the download button should be disabled
- When reviewing code, you can hide whitespaces to simplify the review process
=> [Update] Refactor DownloadVectorTilesToLocalCacheView

README.md, Shared/Supporting Files/Views/AboutView.swift
This PR does 3 things
- Close #232 to add a "Feature" section to give people a glance at what the app offers
- Close #309 to add visual importance to the API key section, so that people won't miss the step to sign up and get a key before running the app for the first time, and they can see the basemap instead of a blank screen.
- Bump year to 2024 🥳 
Preview: https://github.com/Esri/arcgis-maps-sdk-swift-samples/blob/Ting/Update-RootREADME/README.md
=> [Update] README content and year

iOS/Info.plist
This PR implements adds `ITSAppUsesNonExemptEncryption` to the `Info.plist` to prevent a `Missing compliance` warning shown when the the app is uploaded to TestFlight. This allow for future automation of the process. 
- `swift/issues/3435`
- The Sample Viewer builds as expected.
=> [Update] Sample Viewer encryption info

iOS/Info.plist
This PR adds a category to the `Info.plist` to fix an `Asset validation` error that would be thrown when uploading the project to TestFlight as a Mac app.
- `swift/issues/3435`
=> [Fix] Add category info

Shared/Supporting Files/Views/SampleInfoView.swift
This PR replace deprecated API.
- [edgesIgnoringSafeArea(_:)](https://developer.apple.com/documentation/swiftui/view/edgesignoringsafearea(_:)) is deprecated, [ignoresSafeArea(_:edges:)](https://developer.apple.com/documentation/swiftui/view/ignoressafearea(_:edges:)) is used instead.
Open a source code pane, the view should still extend all the way to the bounds.
=> [Update] Replace deprecated safe area API in SampleInfoView

Shared/Samples/Configure clusters/README.metadata.json, Shared/Samples/Display clusters/README.metadata.json
This PR adds the values to the `redirect_from` field in the metadatas of the clustering samples (`Configure clusters` & `Display clusters`). This is due to the samples being renamed in #348.
- `swift/issues/5089`
=> [Update] Add `redirect_from` links to clustering samples

Shared/Samples/Manage bookmarks/ManageBookmarksView.swift
This PR updates `Manage bookmarks` samples to remove bookmarks using the previous broken [removeBookmarks(_:)](https://developers.arcgis.com/swift/api-reference/documentation/arcgis/geomodel/removebookmarks(_:)) method. It also adds a comment about a SwiftUI bug with the `EditButton`.
The remove bookmark methods were fixed in: 
- `swift/issues/4898`
- Load the sample using `200.4.0`.
- Open the list of bookmarks and remove one.
- Close and reopen the list to ensure the given bookmark was actually removed.
=> [Update] Manage bookmarks bookmark removal

Samples.xcodeproj/project.pbxproj, Samples.xcodeproj/xcshareddata/xcschemes/Samples.xcscheme, Shared/Supporting Files/Views/FavoritesView.swift, Shared/Supporting Files/Views/SampleDetailView.swift, Shared/Supporting Files/Views/Sidebar.swift
This PR replaces [`navigationBarTrailing`](https://developer.apple.com/documentation/swiftui/toolbaritemplacement/navigationbartrailing) with `topBarTrailing` as the new API is back deployed to iOS 14+.
This PR also bumps up the Xcode project file recommended settings check to Xcode 15.3.
- Go to the changed places and see if the change look good on both iOS and Mac Catalyst.
=> [Update] Replace deprecated API `navigationBarTrailing`

Scripts/CI/common.py, Scripts/CI/metadata_checker.py
This PR updates the CI style check to ensure the category in the metadata is valid.
Closes #337 
- Change the category in a sample's metadata to an invalid value.
- Run the style check on sample to ensure the check works.
- E.g., `python3 Scripts/CI/metadata_checker.py -s "Shared/Samples/Display map/"`.
=> [Update] Add metadata category checking

Shared/Samples/Animate 3D graphic/Animate3DGraphicView.Model.swift, Shared/Samples/Animate 3D graphic/Animate3DGraphicView.swift
This PR fixes a bug in the `Animate 3D graphic` sample where the plane animation would slow when a sheet was opened. The fix replaces the `Timer` with a `CADisplayLink` and instead adjusts the speed by skipping frames. As a result, the speed `Slider` in the "Mission Settings"  was replaced with a `Picker`.
This PR also adds an animation to minimap to close #344.
- `swift/issues/5130`
- Open the "Mission" sheet in the sample.
- Ensure the animation behind the sheet doesn't slow.
- Use the picker to adjust the speed of the animation.
=> [Fix] `Animate 3D graphic` animations

Shared/Samples/Augment reality to show hidden infrastructure/AugmentRealityToShowHiddenInfrastructureView.ARSceneView.swift
This PR implements a workaround for a bug in the `Augment reality to show hidden infrastructure` sample where it would intermittently crash when quickly switching between the map and scene view. The fix uses a basemap style without vector titles.
- `ping/issues/1650`
- Ensure you can quickly switch between the map and scene view several times without crashing.
=> [Fix] `Augment reality to show hidden infrastructure` scene view crash

Shared/Samples/Create and edit geometries/README.metadata.json
This PR updates `Create and edit geometries`, adds missing redirect from link for https://developers.arcgis.com/swift/sample-code/sketch-on-map/
- Close #376 
See tomorrow in next site build.
=> [Update] Add `redirect_from` link to Create and edit geometries

Scripts/DowloadPortalItemData.swift
This PR updates the `DowloadPortalItemData` script in the Sample Viewer to use Swift concurrency instead of GCD.
URL to script: [DowloadPortalItemData.swift](https://github.com/Esri/arcgis-maps-sdk-swift-samples/blob/Caleb/Update-DownloadPortalItemScriptAsync/Scripts/DowloadPortalItemData.swift)
Follow up PR to #361.
- `swift/issues/4892`
- Delete the `Portal Data` folder or remove entires from the `.downloaded_items.plist`.
- Build the project and view the Log to ensure the files downloaded as expected.
- Open some sample using the resources to ensure they don't crash, e.g., `Animate 3d graphic`.
=> [Update] Remove `DowloadPortalItemData` script GCD

Shared/Samples/Display clusters/DisplayClustersView.swift, Shared/Samples/Display clusters/README.md, Shared/Samples/Display clusters/README.metadata.json
This PR updates the design for the  `Display clusters` sample to add a list displaying a tapped cluster's geoelements.
URL to README: [REAMDE](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/Update-DisplayClustersDesign/Shared/Samples/Display%20clusters)
**Note:** The screenshot was not updated due to https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/676.
- `swift/issues/5165`
- Tap on a cluster to see the list of geoelements in the floating panel.
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - iPhone 15 Pro - 2024-04-09 at 16 29 37](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/90aa1d37-a490-4400-879b-a23b012eb358)    |    ![Simulator Screenshot - iPhone 15 Pro - 2024-04-09 at 16 58 …
=> [Update] `Display clusters` design

iOS/Info.plist
App Store Connect review rejected with the following comment
> If the macOS app requests access to location data, include the [NSLocationUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationusagedescription?language=occ) key on the info.plist. The [NSLocationWhenInUseUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationwheninuseusagedescription) key is only for iOS apps.
Include this key to make ASC reviewers happy. 🫤
From reading this article: https://developer.apple.com/documentation/corelocation/requesting_authorization_to_use_location_services
> On macOS, When in Use and Always authorizations are functionally equivalent. Because macOS apps continue to run in the …
=> [Update] Add `NSLocationUsageDescription` for Mac Catalyst app

Shared/Samples/Add features with contingent values/AddFeaturesWithContingentValuesView.AddFeatureView.swift, Shared/Samples/Add features with contingent values/AddFeaturesWithContingentValuesView.Model.swift, Shared/Samples/Add features with contingent values/AddFeaturesWithContingentValuesView.swift
This PR fixes an issue in the `Add features with contingent values` sample where the "Cancel" button on the "Add Bird Nest" sheet would not remove a feature if the sheet contained valid contingencies values. See feedback [here](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/369#pullrequestreview-1992725338).
- N/A (quick fix)
- Ensure both the "Cancel" and "Done" buttons in the sample work as expected.
=> [Fix] `Add features with contingent values` cancel button

Shared/Samples/Create and edit geometries/CreateAndEditGeometriesView.swift
This PR fixes the retain cycle discussed in #153 .
- #153 
use `deinit` to see if the model is deallocated after sample is closed.
```swift
deinit {
print("✅ cleared")
}
```
=> [Fix] Resolve the Task introduced retain cycle

Shared/Supporting Files/Views/CategoriesView.swift
This PR fixes a bug where the title of the category would be cut off on iPhone Pro Max when in landscape mode. This fix scales the icon and title with the category tile size. As a result, the icon/title are now different sizes on iPad and Mac Catalyst.
- `swift/issues/5250`
- Run on Pro Max in landscape mode to see if any of the text is cut off.
- Ensure that the icons/titles look good on other platforms.
|Before|After|
|:-:|:-:|
|    <img src="https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/8b07edb1-9659-45c4-9241-af1bc16b00da" alt="Pro Max - Before">   |    <img src="https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/486a9d41-1fa0-49a3-908b-a0dbc98e1133" alt="Pro Max - After">    |
|    ![iPad - …
=> [Fix] Category title cut off on Pro Max

Shared/Samples/Browse building floors/BrowseBuildingFloorsView.swift
This PR updates the floor filter in the `Browse building floors` sample to adjust its position based on the attribution bar height.
- `swift/issues/5280`
- Tap the attribution bar to see the floor filters adjust.
- Ensure the sample otherwise works as before.
|Before|After|
|:-:|:-:|
|    <img src="https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/ecc71b7f-14d5-4dfc-90f4-4b45e7fdfa11" alt="Simulator Screenshot - iPhone 15 Pro - 2024-04-24 at 16 25 41" width="276">    |    <img src="https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/897b98df-1e56-4efe-a1ba-b686a706d4f2" alt="Simulator Screenshot - iPhone 15 Pro - 2024-04-24 at 16 33 50" width="276">    |
=> [Update] Add `Browse building floors` floor filter height adjustment

Shared/Samples/Configure basemap style parameters/ConfigureBasemapStyleParametersView.swift
Related to recent API changes. They weren't intended to introduce build errors, so these changes and the API changes may need to be reverted before the next release. For now, addressing them was the easiest approach.
=> [Fix] Address build error and warnings in ConfigureBasemapStyleParametersView.swift

Shared/Samples/Animate 3D graphic/Animate3DGraphicView.SettingsView.swift, Shared/Samples/Find route around barriers/FindRouteAroundBarriersView.Views.swift, Shared/Samples/Group layers together/GroupLayersTogetherView.swift, Shared/Supporting Files/Models/Sample.swift
Addresses the following errors when building with complete strict concurrency enabled:
=> [Setup] Address complete strict concurrency errors

Shared/Samples/Show device location with NMEA data sources/README.md, Shared/Samples/Show device location with NMEA data sources/ShowDeviceLocationWithNMEADataSourcesView.Model.swift, iOS/Info.plist
This PR add support for Emlid devices to the `Show device location with NMEA data sources` sample.
- `swift/issues/5042`
=> [Update] Add Elmid support to NMEA sample

Shared/Samples/Create and save KML file/CreateAndSaveKMLView.swift, Shared/Samples/Create mobile geodatabase/CreateMobileGeodatabaseView.Model.swift, Shared/Samples/Show grid/ShowGridView.swift, Shared/Supporting Files/Extensions/String.swift, Shared/Supporting Files/Models/Sample.swift
Fix some easy to fix concurrency warnings. Mostly just `static var = ` -> `static var` computed
To test, enable strict concurrency = complete from build settings.
|Warnings|
|-|
|![iShot_2024-07-02_16 05 04](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/9660181/7a55c894-4d10-4b87-b411-88dcc504682f)|
|![iShot_2024-07-02_16 05 54](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/9660181/9fc7a28e-c33c-404a-87c0-c1e282323668)|
|![iShot_2024-07-02_16 08 36](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/9660181/caa62e4e-4b8f-4a9d-b6b4-9d85f5e45d4a)|
=> [Fix] Strict concurrency warnings

Shared/Samples/Snap geometry edits/README.md, Shared/Samples/Snap geometry edits/README.metadata.json, Shared/Samples/Snap geometry edits/SnapGeometryEditsView.GeometryEditorMenu.swift, Shared/Samples/Snap geometry edits/SnapGeometryEditsView.GeometryEditorModel.swift
This PR updates `Snap geometry edits`
URL to README: https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/destiny/Use-reticle-vertex-tool-in-Snap-geometry-edits-sample/Shared/Samples/Snap%20geometry%20edits#readme
This PR uses the reticle vertex tool on touch screen devices.
- `swift/issues/5730`
Should `ReticleVertexTool` be added to the relevant_apis metadata? I added it but it caused an inconsistent metadata error.
=> [Update] Use reticle in Snap geometry edits sample

Shared/Supporting Files/Views/FavoritesView.swift
This PR fixes a bug where the "Edit" button in the Favorites view causes other samples to be untappable. The fix sets the environment editing mode to `.inactive` when the Favorites view is dismissed so that other views that show a list of samples are not displayed with an `.active` editing mode. 
- `swift/issues/5405`
- Enter the Favorites category in the Sample Viewer.
- Tap the "Edit" button and back out of the category.
- Enter another category and verify that the samples can be opened.
=> [Fix] Editing mode bug in favorites view

Samples.xcodeproj/project.pbxproj, Samples.xcodeproj/xcshareddata/xcschemes/Samples.xcscheme
This PR changes the "Product Name" of the "Samples" target to "ArcGIS Maps SDK Samples", after the "App Information" > "Name" is changed from "ArcGIS Maps Swift Samples" to "ArcGIS Maps SDK Samples", per App Store reviewer request.
> Guideline 5.2.5 - Legal - Intellectual Property. 
> Your app's metadata includes content that is similar to designs or terms used for Apple products and services and may cause confusion for users. Specifically, your metadata includes:
> - Terms for Swift in the app name in an inappropriate manner.
> - Terms for Swift in the app name that displays on the device. 
and…
> Guideline 2.3.8 - Performance
> We noticed that your app name to be displayed on the App Store does not sufficiently match the name of the app displayed when installed on macOS.
> - App Store …
=> [Setup] Change the product name per App Store reviewer request

Shared/Samples/Play KML tour/README.metadata.json
This PR updates the `Play KML tour` category to match the design and [Kotlin implementation](https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/blob/main/play-kml-tour/README.metadata.json).
=> [Fix] `Play KML tour` category

Shared/Samples/Show service area/ShowServiceAreaView.swift
This PR fixes a bug in the `Show service area` sample where the time break steppers (or sliders) would not work on iOS/iPadOS 16. The best I could come up with was replacing the `Menu` with a `popover`. Let me know if you think of a better solution, though.
- `swift/issues/5776`
- Ensure the sample still works as expected.
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - iPhone 14 Pro - 2024-07-22 at 14 27 18](https://github.com/user-attachments/assets/ab6dc933-f596-4d0d-b1b4-07473482bed0)    |    ![Simulator Screenshot - iPhone 14 Pro - 2024-07-22 at 16 38 08](https://github.com/user-attachments/assets/d4cb3af7-49c4-4d6b-abaa-a7084a0497e0)    |
=> [Fix] `Show service area` time breaks steppers

Shared/Samples/Create and edit geometries/CreateAndEditGeometriesView.swift
This PR sets the vertex tool in the `Create and edit geometries` sample based on [this](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/452#discussion_r1688506167) feedback.
Use a shape tool and then try to edit a `Point` or `Multipoint` geometry.
=> [Fix] Set vertex tool in `Create and edit geometries`

Shared/Samples/Snap geometry edits/SnapGeometryEditsView.swift
This PR fixes a bug in `Snap geometry edits` where not all the  "Individual Source Snapping" toggles would show up if "Snap Settings" was pressed before the map view was finished drawing. The fix enables the button after the map view has finished drawing instead of after the operational layers have loaded.
- `swift/issues/5775`
- Tap "Snap Settings" right after it becomes enabled to ensure all the toggles show up.
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - iPhone 15 Pro - 2024-07-22 at 14 29 24](https://github.com/user-attachments/assets/57ad5557-625c-4267-977b-ff03d8166a63)    |    ![Simulator Screenshot - iPhone 15 Pro - 2024-07-22 at 18 11 22](https://github.com/user-attachments/assets/cdde0105-97a2-4ad6-b68e-fe03c55a69b2)    |
=> [Fix] `Snap geometry edits` snap settings

Shared/Samples/Identify features in WMS layer/IdentifyFeaturesInWMSLayerView.swift
This PR updates `Identify features in WMS layer` to dismiss the callout before async identify operation, so that the sample is more responsive.  
- Ensure the sample otherwise works as before.
=> [Update] `Identify features in WMS layer` callout dismissal

Shared/Samples/Create and edit geometries/CreateAndEditGeometriesView.swift
This PR fixes a bug in the `Create and edit geometries` sample introduced in #452 by setting the selected graphic to `nil` when editing is cancelled. Otherwise the model still has the selected graphic set which causes unexpected behavior when adding a new graphic, resulting in the previously selected graphic to disappear.
=> [Fix] Editing bug in `Create and edit geometries`

Shared/Samples/Create dynamic basemap gallery/CreateDynamicBasemapGalleryView.Views.swift
This PR updates `Create dynamic basemap gallery` to remove the `BasemapStyleLanguage` hashable conformance as it was added at the API level.
- `swift/issues/5801`
- Ensure the project builds using swift daily `200.5.0-4310`.
=> [Fix] Remove `Create dynamic basemap gallery` hashable conformance

Shared/Samples/Augment reality to show hidden infrastructure/AugmentRealityToShowHiddenInfrastructureView.swift, Shared/Samples/Search for web map/SearchForWebMapView.swift
This PR adds a navigation bar back button to the following samples:
- `Augment reality to show hidden infrastructure`
- `Search for web map` 
- `swift/issues/5798`
- Verify back button appears in samples.
`Augment reality to show hidden infrastructure`
`Search for web map`
=> [Fix] Add navigation bar back button to samples

Shared/Samples/Edit with branch versioning/EditWithBranchVersioningView.Model.swift, Shared/Samples/Edit with branch versioning/EditWithBranchVersioningView.swift
This PR updates `Edit with branch versioning` to automatically switch to a branch when it is created. This is to match the other implementation of the other platforms. I updated the to status overlay to only show the current branch name for the same reason.
- `swift/issues/5789`
- Create a branch and ensure you can edit a feature without having to switch branches.
=> [Update] `Edit with branch versioning` version creation

Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.SettingsView.swift, Shared/Samples/Add features with contingent values/AddFeaturesWithContingentValuesView.AddFeatureView.swift, Shared/Samples/Animate 3D graphic/Animate3DGraphicView.swift, Shared/Samples/Change map view background/ChangeMapViewBackgroundView.SettingsView.swift, Shared/Samples/Configure clusters/ConfigureClustersView.SettingsView.swift, Shared/Samples/Create load report/CreateLoadReportView.Views.swift, Shared/Samples/Densify and generalize geometry/DensifyAndGeneralizeGeometryView.SettingsView.swift, Shared/Samples/Generate offline map with custom parameters/GenerateOfflineMapWithCustomParametersView.CustomParameters.swift, Shared/Samples/Orbit camera around object/OrbitCameraAroundObjectView.swift, Shared/Samples/Set visibility of subtype sublayer/SetVisibilityOfSubtypeSublayerView.Views.swift, Shared/Samples/Show viewshed from point in scene/ShowViewshedFromPointInSceneView.ViewshedSettingsView.swift, Shared/Samples/Style symbols from mobile style file/StyleSymbolsFromMobileStyleFileView.SymbolOptionsListView.swift, Shared/Supporting Files/Views/AboutView.swift
This PR updates the samples and sample viewer to use `LabeledContent` to display label/value pairs instead of using a `HStack` or `badge(_:)` modifier. The affected samples should be functionally equivalently with minimal UI changes. Generally, the value now has a `secondary` foreground style if it didn't already.
- `swift/issues/5822`
- Ensure that the label/value pairs display as expected in the affected samples.
Replacing `FavoritesView.favoriteSamples` in `arcgis-maps-sdk-swift-samples/Shared/Supporting Files/Views/FavoritesView.swift` with the following code will load all of the affected samples in the "Favorites" category for easy testing.
<details><summary>Test Code</summary><p>
```swift
private var favoriteSamples: [Sample] {
let sampleViews: [any View] = [ …
```
=> [Update] Use `LabeledContent` in samples

Shared/Samples/Augment reality to show hidden infrastructure/AugmentRealityToShowHiddenInfrastructureView.swift, Shared/Samples/Search for web map/SearchForWebMapView.swift, Shared/Supporting Files/Views/ContentView.swift
This PR fixes a regression where opening the `Search for web map` sample would just show "No Sample Selected" on iPhone (iOS 17). This was caused by the navigation stack added in  #477. Those changes were reverted, and the stack was moved to the `NavigationSplitView` detail. This solution should work for samples that use a navigation link in the future.
- `swift/issues/5798`
Test the `Search for web map` and `Augment reality to show hidden infrastructure` samples:
- On iPhone, ensure the samples launch as expected.
- On iPad, ensure the samples have a navigation back button after clicking the navigation link in landscape mode.
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - 1 - iPhone 15 Pro - 2024-07-30 at 11 48 56](https://github.com/user-attachments/assets/81c4fe50-fcc8-49cf-ad6e …
=> [Fix] `Search for web map` navigation bugs

Shared/Samples/Add features with contingent values/AddFeaturesWithContingentValuesView.Model.swift, Shared/Samples/Animate 3D graphic/Animate3DGraphicView.Model.swift, Shared/Samples/Augment reality to navigate route/AugmentRealityToNavigateRouteView.ARSceneView.swift, Shared/Samples/Augment reality to navigate route/AugmentRealityToNavigateRouteView.swift, Shared/Samples/Create load report/CreateLoadReportView.swift, Shared/Samples/Densify and generalize geometry/DensifyAndGeneralizeGeometryView.SettingsView.swift, Shared/Samples/Edit feature attachments/EditFeatureAttachmentsView.Model.swift, Shared/Samples/Find route around barriers/FindRouteAroundBarriersView.Model.swift, Shared/Samples/Find route in mobile map package/FindRouteInMobileMapPackageView.Models.swift, Shared/Samples/Find route in transport network/FindRouteInTransportNetworkView.Model.swift, Shared/Samples/Generate offline map with custom parameters/GenerateOfflineMapWithCustomParametersView.CustomParameters.swift, Shared/Samples/Geocode offline/GeocodeOfflineView.Model.swift, Shared/Samples/List spatial reference transformations/ListSpatialReferenceTransformationsView.Model.swift, Shared/Samples/Navigate route with rerouting/NavigateRouteWithReroutingView.Model.swift, Shared/Samples/Navigate route/NavigateRouteView.swift, Shared/Samples/Orbit camera around object/OrbitCameraAroundObjectView.Model.swift, Shared/Samples/Search for web map/SearchForWebMapView.Model.swift, Shared/Samples/Search for web map/SearchForWebMapView.Views.swift, Shared/Samples/Set visibility of subtype sublayer/SetVisibilityOfSubtypeSublayerView.Views.swift, Shared/Samples/Show device location with NMEA data sources/ShowDeviceLocationWithNMEADataSourcesView.swift, Shared/Samples/Style symbols from mobile style file/StyleSymbolsFromMobileStyleFileView.SymbolOptionsListView.swift, Shared/Samples/Validate utility network topology/ValidateUtilityNetworkTopologyView.Model.swift, Shared/Supporting Files/Extensions/String.swift
This PR removes unnecessary imports that were discovered by running the swift lint `unused_import` analyzer rule.
Similar to #257
- Ensure the project builds.
=> [Fix] Remove unused imports

Shared/Samples/Analyze network with subnetwork trace/AnalyzeNetworkWithSubnetworkTraceView.swift, Shared/Samples/Augment reality to collect data/AugmentRealityToCollectDataView.swift, Shared/Samples/Change camera controller/ChangeCameraControllerView.swift, Shared/Samples/Create dynamic basemap gallery/CreateDynamicBasemapGalleryView.Views.swift, Shared/Samples/Find route/FindRouteView.swift, Shared/Samples/Validate utility network topology/ValidateUtilityNetworkTopologyView.swift, Shared/Supporting Files/Views/SamplesSearchView.swift
This PR removes unused declarations that were discovered by running the swift lint `unused_declaration` analyzer rule.
- Ensure the project builds.
=> [Fix] Remove unused declarations

Shared/Samples/Add custom dynamic entity data source/AddCustomDynamicEntityDataSourceView.swift, Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.Model.swift, Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.swift, Shared/Samples/Analyze network with subnetwork trace/AnalyzeNetworkWithSubnetworkTraceView.Model.swift, Shared/Samples/Analyze network with subnetwork trace/AnalyzeNetworkWithSubnetworkTraceView.swift, Shared/Samples/Animate 3D graphic/Animate3DGraphicView.swift, Shared/Samples/Authenticate with OAuth/AuthenticateWithOAuthView.swift, Shared/Samples/Change camera controller/ChangeCameraControllerView.swift, Shared/Samples/Change viewpoint/ChangeViewpointView.swift, Shared/Samples/Create and save KML file/CreateAndSaveKMLView.Views.swift, Shared/Samples/Create and save KML file/CreateAndSaveKMLView.swift, Shared/Samples/Create load report/CreateLoadReportView.Model.swift, Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.MapPicker.swift, Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.Model.swift, Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.swift, Shared/Samples/Edit geodatabase with transactions/EditGeodatabaseWithTransactionsView.Model.swift, Shared/Samples/Find nearest vertex/FindNearestVertexView.swift, Shared/Samples/Identify layer features/IdentifyLayerFeaturesView.swift, Shared/Samples/Run valve isolation trace/RunValveIsolationTraceView.swift, Shared/Samples/Set visibility of subtype sublayer/SetVisibilityOfSubtypeSublayerView.Model.swift, Shared/Samples/Set visibility of subtype sublayer/SetVisibilityOfSubtypeSublayerView.swift, Shared/Samples/Show coordinates in multiple formats/ShowCoordinatesInMultipleFormatsView.swift, Shared/Samples/Show device location with NMEA data sources/FileNMEASentenceReader.swift, Shared/Samples/Show device location with NMEA data sources/ShowDeviceLocationWithNMEADataSourcesView.swift, Shared/Samples/Show realistic light and shadows/ShowRealisticLightAndShadowsView.swift, Shared/Samples/Trace utility network/TraceUtilityNetworkView.Views.swift
This PR updates the access levels of types and members used by samples to make them more encapsulated. This was done to: 
- Prevent types and members being reused in other samples. (Samples should be stand alone to allow users to copy and paste them, see related [comment](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/372#discussion_r1567718805).)
- Prevent existing declarations interfering with new ones. (E.g., the internal `Model` used by `Edit geodatabase with transactions` was preventing any new samples from implementing their own file-private `Model`.)
Overview of changes (corresponding to a commit):
- Make types file-private or nested (or both).
- Make extensions private were possible.
- Make sample view members (properties, methods, & nested types) private were …
=> [Update] Sample type and member access levels

Shared/Samples/Create load report/CreateLoadReportView.Model.swift, Shared/Samples/Create mobile geodatabase/CreateMobileGeodatabaseView.Model.swift, Shared/Samples/Find route in mobile map package/FindRouteInMobileMapPackageView.Models.swift, Shared/Samples/Show device location with NMEA data sources/FileNMEASentenceReader.swift, Shared/Samples/Show viewshed from point on map/ShowViewshedFromPointOnMapView.swift
This PR updates the samples to use type annotation for array and dictionary initialization.
Closes #493
- Ensure the project builds.
=> [Update] Use type annotation for empty arrays and dictionaries

.gitignore, .swiftlint.yml, Scripts/CI/run_swift_lint_analyzer.sh, Scripts/run_swift_lint_analyzer.sh
This PR adds to swift lint analyzer rules with a bash script to run them. These will be run as part of release verification.
The relevant errors/warning for the these rules were fixed here:
- `typesafe_array_init` : No errors
- `unused_declaration`: #490
- `unused_import`: #489 
- `swift/issues/5873`
Run `run_swift_lint_analyzer.sh`  in `Scripts/CI` (may take a while).
- **Note:** The many top level sample views produce unused declaration warnings due to the current project structure. This is expected.
=> [Setup] Add swift lint analyzer rules

Shared/Samples/Augment reality to collect data/README.md, Shared/Samples/Create symbol styles from web styles/README.md, Shared/Samples/Find route in transport network/README.md, Shared/Samples/Play KML tour/README.md, Shared/Samples/Show mobile map package expiration date/README.md, Shared/Samples/Style symbols from mobile style file/README.md
This PR replaces "ArcGIS Runtime" with "ArcGIS Maps SDK" in the documentation. It also updates `arcgisruntime.maps.arcgis.com` links to `www.arcgis.com`.
Closes #414
- Ensure the updated links work.
=> [Update] Remove runtime references

Scripts/DowloadPortalItemData.swift, Shared/Samples/Navigate route with rerouting/NavigateRouteWithReroutingView.Model.swift, Shared/Supporting Files/Extensions/Array+RawRepresentable.swift
This PR addresses the remaining linter warnings. 
I hoped that the change in https://github.com/realm/SwiftLint/pull/5601 get into SwiftLint 0.56.1, but it didn't and I don't want to wait for it. In our case, this change shouldn't cause a problem, as the data being converted to string are all known to be valid. Since this linter warning is addressed in the SDK, let's do it for the samples.
See https://github.com/realm/SwiftLint/issues/5263
- `swift/pull/5695`
Build with latest SwiftLint and no more linter warnings.
=> [Update] Fix linter warnings for string <-> data conversion

Shared/Samples/Analyze network with subnetwork trace/AnalyzeNetworkWithSubnetworkTraceView.swift
prefer_type_checking rule: https://realm.github.io/SwiftLint/prefer_type_checking.html
introduced in SwiftLint 0.55.0
=> [Update] Fix "Prefer Type Checking" linter warning

Shared/Samples/Animate 3D graphic/Animate3DGraphicView.SettingsView.swift, Shared/Samples/Augment reality to navigate route/AugmentRealityToNavigateRouteView.swift, Shared/Samples/Create symbol styles from web styles/CreateSymbolStylesFromWebStylesView.swift, Shared/Samples/Display dimensions/DisplayDimensionsView.swift, Shared/Samples/Display map from mobile map package/DisplayMapFromMobileMapPackageView.swift, Shared/Samples/Find route around barriers/FindRouteAroundBarriersView.Views.swift, Shared/Samples/Group layers together/GroupLayersTogetherView.swift, Shared/Samples/Identify KML features/IdentifyKMLFeaturesView.swift
This PR closes #455, #456, #457 . Since Xcode 16 is supported, views are always on main actor.
- `swift/pulls/6067`
Build and run without concurrency warnings.
Please note: this branch targets #508 so it will be merged after it.
=> [Update] Remove MainActor annotation from views

Scripts/create-metadata-from-README.py
This PR fixes an error with the `create-metadata-from-README.py` script introduced in #501.
- Ensure the script runs without error. Example: `Scripts/create-metadata-from-README.py -c "Shared/Samples/Display map"`
=> [Fix] Create metadata script error

Shared/Samples/Snap geometry edits/README.md, Shared/Samples/Snap geometry edits/SnapGeometryEditsView.GeometryEditorModel.swift, Shared/Samples/Snap geometry edits/SnapGeometryEditsView.SnapSettingsView.swift
This PR adds "Geometry Guides" and "Feature Snapping" toggles to `Snap geometry edits` corresponding to the updated design.
- `swift/issues/6031`
- Ensure the new toggles work as expected. (See the video in the design for an example if needed).
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - iPhone 16 Pro - 2024-10-09 at 11 57 21](https://github.com/user-attachments/assets/4be77082-0a5c-4422-b02c-da6e896cf85b)    |    ![Simulator Screenshot - iPhone 16 Pro - 2024-10-09 at 11 53 09](https://github.com/user-attachments/assets/a02289ea-6d8f-427c-9ab1-08187d991ced)    |
=> [Update] Add toggles to `Snap geometry edits`

Shared/Samples/Snap geometry edits/README.md, Shared/Samples/Snap geometry edits/SnapGeometryEditsView.GeometryEditorModel.swift, Shared/Samples/Snap geometry edits/SnapGeometryEditsView.SnapSettingsView.swift
This PR fixes build errors with some snap settings boolean names that were change during a recent audit.
- `swift/issues/6031`
- `swift/issues/6009`
- #514
- Ensure the project builds using the latest swift daily.
=> [Fix] Snap settings build errors

Shared/Samples/Add point cloud layer from file/AddPointCloudLayerFromFileView.swift, Shared/Samples/Add point scene layer/AddPointSceneLayerView.swift
This PR fixes a typo with the WorldElevation3D URLs in  `Add point cloud layer from file` & `Add point scene layer`.
Ensure the samples now have elevation.
**Note:** Swift daily is currently required to build.
=> [Fix] WorldElevation3D URL typos

Shared/Samples/Add ENC exchange set/AddENCExchangeSetView.swift, Shared/Samples/Add elevation source from raster/AddElevationSourceFromRasterView.swift, Shared/Samples/Add elevation source from tile package/AddElevationSourceFromTilePackageView.swift, Shared/Samples/Generate offline map with local basemap/GenerateOfflineMapWithLocalBasemapView.swift
Currently, samples with on-demand resources do not support previews. This PR removes some previews that were add by mistake.
- `swift/issues/6248`
=> [Fix] Remove broken previews

Shared/Samples/Snap geometry edits/README.md
This PR adds a comment on haptic feedback to the `Snap geometry edits` readme (to match the updates to the design).
URL to README: [Snap geometry edits](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/Update-SnapGeometryEditsReadme/Shared/Samples/Snap%20geometry%20edits)
- `swift/issues/6230`
=> [Update] Add `Snap geometry edits` haptic feedback doc

Shared/Samples/Show grid/README.md, Shared/Samples/Show grid/README.metadata.json, Shared/Samples/Show grid/ShowGridView.swift
This PR updates `Show grid` in `Visualization` category to include a scene view (matching the updates to the design). 
URL to README: [Show grid](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/Update-ShowGrid/Shared/Samples/Show%20grid)
- `swift/issues/6175`
- Use the picker to switch between the geo views.
- Ensure the grid settings still work as expected.
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - 1 - iPhone 16 Pro - 2024-10-25 at 17 55 30](https://github.com/user-attachments/assets/e661f18d-6337-49ca-935a-504669746560)    |    ![Simulator Screenshot - 1 - iPhone 16 Pro - 2024-10-25 at 17 52 33](https://github.com/user-attachments/assets/03281bb4-7cb9-4af8-a7af-e0570da4014c)    |
=> [Update] `Show grid` to include scene view

Shared/Samples/Configure clusters/ConfigureClustersView.swift
This PR fixes a bug with the `Configure clusters` settings where the "Current Map Scale" wouldn't show the correct value until the map scale was changed.
Open "Clustering Settings" without interacting with the map first and verify that the "Current Map Scale" shows the correct default value.
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - 1 - iPhone 16 Pro - 2024-10-31 at 11 52 42](https://github.com/user-attachments/assets/4e10479f-bfb5-4515-a188-51d85a473b52)    |     ![Simulator Screenshot - 1 - iPhone 16 Pro - 2024-10-31 at 11 53 09](https://github.com/user-attachments/assets/6e618128-00f0-4e63-98cf-02e21f5b52d9)    |
=> [Fix] `Configure clusters` settings state

README.md, Samples.xcodeproj/project.pbxproj
This PR bumps the samples and toolkit version numbers to `200.6.0` in preparation for the release.
=> [Update] Bump version numbers for `200.6.0`

Shared/Samples/Style geometry types with symbols/README.metadata.json
This PR adds a `redirect_from` link to `Style geometry types with symbols` since it replaced `Style point with picture marker symbols` in #496.
- `swift/issues/5786`
Append the `redirect_from` value to `https://developers.arcgis.com` to very the link is valid.
=> [Update] Add `Style geometry types with symbols` redirect from link

Shared/Samples/Add vector tiled layer from custom style/AddVectorTiledLayerFromCustomStyleView.swift, Shared/Samples/Style geometry types with symbols/StyleGeometryTypesWithSymbolsView.Views.swift
This PR fixes some issues discovered while verifying the samples completed for the `200.6.0` release:
- `Add vector tiled layer from custom style`: Removed an unused declaration.
- `Style geometry types with symbols`: Fixed a bug where the pickers wouldn't save state in between closing and opening the popover on Mac Catalyst.
Swift lint also recommended replacing `import SwiftUI` with `import SwiftUICore` in a few samples. It seems like this is an [Apple bug](https://forums.swift.org/t/swiftuicore-vs-swiftui/73722), so I left these as is for now.
- `swift/issues/6285`
- `Add vector tiled layer from custom style`: Verify the project builds.
- `Style geometry types with symbols`: Verify the pickers show the correct values after the "Edit Style" settings are closed and reopened.
=> [Fix] `200.6.0` sample issues

Shared/Samples/Geocode offline/GeocodeOfflineView.swift, Shared/Samples/Query feature table/QueryFeatureTableView.swift, Shared/Samples/Search for web map/SearchForWebMapView.swift, Shared/Supporting Files/Views/CategoriesView.swift, Shared/Supporting Files/Views/FavoritesView.swift, Shared/Supporting Files/Views/SampleLink.swift
This PR fixes some issues related to searching in the samples:
- A bug where some text wouldn't be bolded correctly due to a markdown issue (see screenshots).
- A bug where autocorrect would change the search results would change when un-focusing a search bar. Disabled autocorrect appears to be the default behavior for `.searchable` in iOS 18+, so this fix is for iOS 16 & 17.
- Verify the search bars perform as expected.
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - 1 - iPhone 16 Pro - 2024-11-13 at 16 38 47](https://github.com/user-attachments/assets/da18b9a1-d277-4989-8dc3-4c837ff71b64)    |    ![Simulator Screenshot - 1 - iPhone 16 Pro - 2024-11-13 at 16 38 10](https://github.com/user-attachments/assets/7cd9c0b3-2cf4-4daf-8604-c948f0baa1ea)    |
=> [Fix] Search bugs

Samples.xcodeproj/project.pbxproj, Shared/Supporting Files/Models/Sample.swift, Shared/Supporting Files/Views/SampleDetailView.swift, Shared/Supporting Files/Views/SampleLink.swift, Shared/Supporting Files/Views/SampleMenuButtons.swift
This PR updates the sample row context menu and adds a new sample toolbar menu with following actions: 
- `View Info` (This replaces the sample info button to save space. Also, this is only present in the toolbar menu since it was much simipler to do it that way.)
- `View on Esri Developer`
- `View on GitHub` (This replaces the Mac Catalyst toolbar button.) 
- `Favorite`/`Unfavorite`
Closes #407
- Ensure all of the menu actions work in the context menu (long press on a sample row) and the sample toolbar menu (circle ellipse button).
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - 1 - iPhone 16 Pro - 2024-11-15 at 12 27 26](https://github.com/user-attachments/assets/77811b05-e615-421e-b6c8-70b8c71cf4c4)    |    ![Simulator Screenshot - 1 - iPhone 16 Pro - 2024-11-15 at 12 26 …
=> [Update] Add sample action menu

Shared/Samples/Query feature count and extent/README.metadata.json
This PR changes the `Query feature count and extent` category to the more fitting "Search and Query".
=> [Fix] `Query feature count and extent` category

Shared/Supporting Files/Extensions/View+ErrorAlert.swift
This PR updates the `View.errorAlert(presentingError:)` message to better describe the errors it presents. Since most of the errors thrown contain their info in their type, it is better to show that rather than the `localizedDescription`.
I messed with the credentials in the [`Add feature layers`](https://github.com/Esri/arcgis-maps-sdk-swift-samples/blob/v.next/Shared/Samples/Add%20feature%20layers/AddFeatureLayersView.swift#L71) sample to throw some errors.
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - 1 - iPhone 16 Pro - 2024-12-12 at 18 20 58](https://github.com/user-attachments/assets/906925cc-7825-4646-833b-0bd50ac087e6)    |     ![Simulator Screenshot - 1 - iPhone 16 Pro - 2024-12-12 at 18 19 57](https://github.com/user-attachments/assets/9ba2ac56-1f60-467e-97e2-d39980e4e5e …
=> [Update] Make `errorAlert` message more descriptive

Shared/Samples/Create planar and geodetic buffers/README.md
This PR updates the README for  `Create planar and geodetic buffers`.
- `swift/issues/6401`
Look for typos in README.
Because the API is called `GeometryEngine.geodeticBuffer`, I opt for using the word "geodetic" throughout the README.
=> [Update] Add details to README for Create planar and geodetic buffers

Shared/Supporting Files/Views/SampleLink.swift
This PR removes the viewpoint jump bug workaround since the issue has now been resolved in the SDK. Tested on iOS & iPadOS 16-18.
- `swift/issues/1451`
- Replace `arcgis-maps-sdk-swift-toolkit` with `swift-toolkit-daily`.
- Open a keyboard in a sample, such as "Geocode offline".
- Rotate the device to landscape mode.
- Ensure the map view's viewpoint doesn't jump to the bottom of the map.
=> [Update] Remove viewpoint jump workaround

README.md, Samples.xcodeproj/project.pbxproj
This PR bumps the samples and toolkit version numbers to `200.7.0` in preparation for the upcoming release.
Note that the project currently doesn't build since the 200.7 toolkit hasn't been released yet.
- `swift/issues/6687`
=> [Update] Bump version numbers for `200.7.0`

Shared/Samples/Snap geometry edits/README.md
This PR updates the `Snap geometry edits` README to include info on `SnapSourceSettings.childSourceSettings` (since it was added to the design).
URL to README: [Snap geometry edits](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/Update-SnapGeometryEditsReadme/Shared/Samples/Snap%20geometry%20edits)
- `common-samples/issues/3972`
=> [Update] Add `SnapSourceSettings.childSourceSettings` info

Shared/Samples/Snap geometry edits/SnapGeometryEditsView.GeometryEditorMenu.swift, Shared/Samples/Snap geometry edits/SnapGeometryEditsView.GeometryEditorModel.swift
This PR removes the use of `FreehandTool` and `ShapeTool` from `Snap geometry edits` since the tools do not support snapping. I also updated the model since the sample now only uses one tool per run (`VertexTool` on Mac Catalyst and `ReticleVertexTool` on iOS and iPadOS). The "Uniform Scale" toggle is also now optionally hidden since it doesn't have an effect on the reticle, which makes it unnecessary on iOS.
- Ensure the sample otherwise works as expected.
|Before|After|
|:-:|:-:|
|    ![Simulator Screenshot - 1 - iPhone 16 Pro - 2025-04-03 at 09 57 40](https://github.com/user-attachments/assets/b12fca12-899d-4bfe-a9a9-e4e21b103301)    |    ![Simulator Screenshot - 1 - iPhone 16 Pro - 2025-04-03 at 16 33 24](https://github.com/user-attachments/assets/d58122e7-d2ff-4090-b8b2-fdbbd57ac626) …
=> [Update] Remove non snapping tools from `Snap geometry edits`

Shared/Samples/Show device location using indoor positioning/README.md, Shared/Samples/Show device location using indoor positioning/README.metadata.json, Shared/Samples/Show device location using indoor positioning/ShowDeviceLocationUsingIndoorPositioningView.Model.swift
This PR removes "table" references from `Show device location using indoor positioning` since the sample no longer uses the `IndoorsLocationDataSource`  table-based initializer (as of #565). See related [comment](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/565#discussion_r2033594943).
URL to README: [Show device location using indoor positioning](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/Update-RemoveTableReferences/Shared/Samples/Show%20device%20location%20using%20indoor%20positioning)
- `common-samples/pull/3975`
=> [Update] Remove `Show device location using indoor positioning` "table"  references

Samples.xcodeproj/project.pbxproj, Shared/Supporting Files/Extensions/Bundle.swift, Shared/Supporting Files/Extensions/EnvironmentValues+RequestReviewModel.swift, Shared/Supporting Files/Views/AboutView.swift, Shared/Supporting Files/Views/ContentView.swift, Shared/Supporting Files/Views/SampleDetailView.swift
This PR adds App Store review requests to the Samples app. The review request will appear after the user opens 4 samples and then pauses on the "Categories" page for a couple of seconds. The request will also only appear once per version. The alert will not show if the app is built for release or ran on simulator, to prevent interfering with development. This workflow is heavily derived from Apple's [Requesting App Store reviews](https://developer.apple.com/documentation/storekit/requesting-app-store-reviews) sample code.
- `swift/issues/6333`
- Comment out [this check](https://github.com/Esri/arcgis-maps-sdk-swift-samples/blob/Caleb/New-AppStoreReviews/Shared/Supporting%20Files/Extensions/EnvironmentValues%2BRequestReviewModel.swift#L32-L34) to test with a debug build and on simulator.
- …
=> [Setup] Add App Store review requests

Samples.xcodeproj/project.pbxproj, Shared/Samples/Download vector tiles to local cache/DownloadVectorTilesToLocalCacheView.swift, Shared/Supporting Files/Extensions/View+PagePresentation.swift, Shared/Supporting Files/Views/ContentView.swift, Shared/Supporting Files/Views/FavoritesView.swift, Shared/Supporting Files/Views/SampleDetailView.swift
This PR fixes an issue where sheets would display smaller than expected on iPadOS and Mac Catalyst 18.0+. The only sample that I thought needed this fix was `Download vector tiles to local cache`, since the rest of sheets have content small enough to fit in `PresentationSizing.form`, which appears to be the new default.
- Ensure the affected sheets work as expected.
- About View: Tap on the info button in the categories toolbar.
- Add favorite view: Enter the Favorites category and tap the plus button.
- Sample info view: Enter a sample, tap the ellipsis button, and tap "View Info".
- `Download vector tiles to local cache` sample: Tap "Download Vector Tiles" button in the sample.
|Before|After|
|:-:|:-:|
|    ![Screenshot 2025-04-21 at 4 39 …
=> [Fix] 18.0 sheet sizes

Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.SettingsView.swift, Shared/Samples/Add dynamic entity layer/AddDynamicEntityLayerView.VehicleCallout.swift, Shared/Samples/Change map view background/ChangeMapViewBackgroundView.SettingsView.swift, Shared/Samples/Create mobile geodatabase/CreateMobileGeodatabaseView.swift, Shared/Samples/Show mobile map package expiration date/ShowMobileMapPackageExpirationDateView.swift
I noticed that some samples are using `formatted()` when they could instead pass the format style as a separate parameter, allowing SwiftUI to efficiently decide when to format the value. These changes replace uses of `formatted()` in views with the more appropriate SwiftUI formatting API.
=> Use `formatted()` in fewer places

Samples.xcodeproj/project.pbxproj, Shared/Samples/Apply hillshade renderer to raster/ApplyHillshadeRendererToRasterView.swift, Shared/Samples/Apply hillshade renderer to raster/README.metadata.json
This PR fixes `Apply hillshade renderer to raster` #592 in `Visualization` category. It replaces the single `srtm.tiff` file and put it in a folder, to ensure the build process passes. For some reason, single file raster doesn't play along very well with our samples…
1. Clean the portal data folder. Either clear all, or delete the "Portal Data/9c802ab0c93a4e45a16311c666fe81c1" and "Portal Data/ae9739163a76437ea02482e1a807b806" folder.
2. Build and run the app. There shouldn't be an error, whereas on v.next there is a build error.
=> [Fix] Replace single raster tiff with a folder

Shared/Samples/Add KML layer with network links/README.md, Shared/Samples/Add WFS layer/README.md, Shared/Samples/Add elevation source from raster/README.md, Shared/Samples/Add elevation source from tile package/README.md
This PR clean up some URLs that contain the "arcgisruntime" org prefix.
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/607#discussion_r2085181465
Open each updated URL and don't see 404. Use `grep -nrF 'runtime' .` to see if there are more "runtime" occurrence in the folder.
=> [Update] Replace runtime org URL prefix

Shared/Samples/Augment reality to navigate route/AugmentRealityToNavigateRouteView.ARSceneView.swift, Shared/Samples/Navigate route/NavigateRouteView.swift
This PR removes superfluous `try` keyword from `for try await in` syntax. Found these while discussing `AsyncStream` with Mary.
=> [Update] Remove `try` keyword from for-await-in

Samples.xcodeproj/project.pbxproj
Adds missing ODR tag for `Shasta_Elevation` in the `Apply blend renderer to hillshade` sample.
Verify project builds and open the `Apply blend renderer to hillshade` sample.
=> [Fix] Add tag for ApplyBlendRendererToHillshade sample

Shared/Samples/Show service area/README.metadata.json
Change category for the sample.
This PR implements `Show service area` in `Routing and Logistics` category. According to the category design doc, Network analysis samples should be in this category, rather than Analysis.
- https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/618#discussion_r2092110078
=> [Update] Category for Show service area sample

Shared/Supporting Files/Views/AboutView.swift
This PR fixes a crash when building the project using the local Swift Package "ArcGIS".
- `swift/issues/7023`
Build the Samples project using local toolkit and local ArcGIS.
=> [Fix] Change local Swift package bundle identifier

Shared/Samples/Add KML layer/AddKMLLayerView.swift, Shared/Samples/Add KML layer/README.md
This PR updates `Add KML layer` in `Layers` category. The current SigWx day 1 outlook data is no longer working, which might due to some faulty links in the KML network link. After discussion, we decided to replace it with a convective outlook data.
- `common-samples/pull/4008`
Run the sample and see the kml show up on this branch, don't show up on v.next.
=> [Update] Replace NOAA KML data in Add KML layer

Shared/Samples/Manage features/ManageFeaturesView.swift
This PR updates `Manage features` with some suggestions that Sarat gave during `200.8.0` certification:
- Enlarges the edit feature menu's hit box since it was hard to press.
- Hides the callout when it is showing and the map is tapped rather than immediately performing another identify.
- Allows the user to select a damage kind attribute value instead of incrementing it.
- `swift/issues/7113`
Other than the added confirmation dialog, there are no UI changes.
=> [Fix] `Manage features` certification issues

Shared/Supporting Files/Views/CategoriesView.swift
The `SampleDetailView` needs an identity to force reinitialize. Because its underlying sample body is `AnyView`, SwiftUI cannot effectively tell the views apart without identity. Thus, if we switch between samples with ODR, the ODR won't re-initialize, which would lead to wrong behaviors or crash.
I missed it when I reviewed #667 [here](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/667/files#diff-b35bada8896ea735015d09e0ca6da223c794c71c1d61a74f487ee11934a31c00L36), so adding it back.
- `swift/issues/7143`
- #234 
On iPad…
- Before change: open 2 ODR samples one by one and see the second sample behaves incorrectly.
- for example, Add raster from file, then Add point cloud layer from file 
- After change: all ODR samples should work correctly.
=> [Fix] Add back missing identity for `SampleDetailView`

Shared/Samples/Set up location-driven geotriggers/SetUpLocationDrivenGeotriggersView.swift
This PR fixes a bug with `Set up location-driven geotriggers` where the first "Current Section" wouldn't always be available. The solution was to kick off the `GeotriggerMonitor.notifications` monitoring loop before calling `GeotriggerMonitor.start()`.
Open `Set up location-driven geotriggers` a few times and ensure the "Current Section" button is always enabled **before** the location display leaves the "Desert".
=> [Fix] `Set up location driven geotriggers` monitoring

Shared/Supporting Files/Views/AboutView.swift
This PR adds a debug textfield to enter a different API key, in the case that a legacy key stops working but we still want to test an older daily build.
- `swift/issues/7131`
- Put in an invalid key to see the app doesn't load basemap
- Put in a valid key to see the app works
- Use reset button to see the app works
=> [Setup] Add debug section to allow swapping API key

Shared/Samples/Add items to portal/AddItemsToPortalView.swift, Shared/Samples/Authenticate with Integrated Windows Authentication/AuthenticateWithIntegratedWindowsAuthenticationView.swift, Shared/Samples/Authenticate with OAuth/AuthenticateWithOAuthView.swift, Shared/Samples/Authenticate with PKI certificate/AuthenticateWithPKICertificateView.swift, Shared/Samples/Authenticate with token/AuthenticateWithTokenView.swift, Shared/Samples/Create and save map/CreateAndSaveMapView.swift, Shared/Samples/Show portal user info/ShowPortalUserInfoView.swift
Redo of #692 since the original was created using the wrong base branch (main):
This PR uses replaces custom authentication methods with [`AuthenticationManager.signOut()`](https://developers.arcgis.com/swift/toolkit-api-reference/documentation/arcgistoolkit/arcgis/authenticationmanager/signout()) in response to this feedback https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/667#discussion_r2226759344 (and fixes a couple of comment issues I noticed in the process).
Closes #671
Ensure the affected samples still perform as expected.
=> [Update] Use `AuthenticationManager.signOut()`

.swiftlint.yml, Shared/Samples/Add vector tiled layer from custom style/AddVectorTiledLayerFromCustomStyleView.swift, Shared/Samples/Apply function to raster from service/ApplyFunctionToRasterFromServiceView.swift, Shared/Samples/Apply scheduled updates to preplanned map area/ApplyScheduledUpdatesToPreplannedMapAreaView.swift, Shared/Samples/Configure electronic navigational charts/ConfigureElectronicNavigationalChartsView.swift, Shared/Samples/Create KML multi-track/CreateKMLMultiTrackView.Model.swift, Shared/Samples/Create and edit geometries/CreateAndEditGeometriesView.swift, Shared/Samples/Create and save KML file/CreateAndSaveKMLView.swift, Shared/Samples/Download preplanned map area/DownloadPreplannedMapAreaView.Model.swift, Shared/Samples/Download vector tiles to local cache/DownloadVectorTilesToLocalCacheView.swift, Shared/Samples/Edit and sync features with feature service/EditAndSyncFeaturesWithFeatureServiceView.Model.swift, Shared/Samples/Edit features with feature-linked annotation/EditFeaturesWithFeatureLinkedAnnotationView.Model.swift, Shared/Samples/Edit geodatabase with transactions/EditGeodatabaseWithTransactionsView.Model.swift, Shared/Samples/Edit geometries with programmatic reticle tool/EditGeometriesWithProgrammaticReticleToolView.swift, Shared/Samples/Generate geodatabase replica from feature service/GenerateGeodatabaseReplicaFromFeatureServiceView.Model.swift, Shared/Samples/Generate offline map with custom parameters/GenerateOfflineMapWithCustomParametersView.Model.swift, Shared/Samples/Generate offline map with local basemap/GenerateOfflineMapWithLocalBasemapView.swift, Shared/Samples/Generate offline map/GenerateOfflineMapView.swift, Shared/Samples/Search for web map/SearchForWebMapView.Model.swift, Shared/Samples/Show device location history/ShowDeviceLocationHistoryView.swift, Shared/Samples/Snap geometry edits with utility network rules/SnapGeometryEditsWithUtilityNetworkRulesView.Model.swift
This is a redo of #690 since the original was accidentally merged into `main`:
This PR updates some SwiftLint rules to match how they are handled in the SDK:
- `force_try` was disabled (In response to [this feedback](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/662#discussion_r2226246455)).
- `notification_center_detachment` was undisabled (since it seemed unneeded).
Closes #590
Ensure the project builds without any warnings.
Below is a diff between the Samples and SDK linter rules after the changes in this PR. (Green lines are the rules that the SDK has and the Samples doesn't. Red is the opposite. Disabled rules are at the top.) Let me know if you think it would make sense to add/remove any other rules.
=> [Update] Linter rules

Shared/Samples/Add custom dynamic entity data source/AddCustomDynamicEntityDataSourceView.Vessel.swift, Shared/Samples/Add custom dynamic entity data source/AddCustomDynamicEntityDataSourceView.swift
This PR updates `Add custom dynamic entity data source` to remove its custom `Geometry` type since `Point` is Decodable and can be used instead. See https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/684#discussion_r2277364282.
- Ensure that the dynamic entities in `Add custom dynamic entity data source` still move as expected.
=> [Update] `Add custom dynamic entity data source` - Remove custom Geometry type

Shared/Samples/Manage features/ManageFeaturesView.swift, Shared/Supporting Files/Models/OnDemandResource.swift, Shared/Supporting Files/Views/DownloadOfflineResourcesView.swift
This PR fixes the appendInterpolation warning when compiled with Xcode 26. 
- `swift/issues/7333`
Build with both Xcode 16.4 and 26.0 and see no warning.
=> [Fix] appendInterpolation warning
